# Pandas DataFrame — Complete Guide for AIML Students

### Topics: Introduction → Series → DataFrame → Indexing → Cleaning → Manipulation → GroupBy → Merge → DateTime → I/O → Large Datasets

---
> **Learning Objective:** Master Pandas, the most essential data manipulation library in Python for Machine Learning and Data Science.

## Table of Contents
1. Import Required Libraries
2. Introduction to Pandas
3. Characteristics of Pandas
4. Series — 1D Labeled Array
5. Creating a Series
6. DataFrame Introduction and Structure
7. Properties of DataFrame
8. Creating a DataFrame
9. Adding Columns to DataFrame
10. Renaming Columns
11. Indexing and Data Selection (loc & iloc)
12. DataFrame Slicing
13. set_index & Hierarchical Indexing
14. Data Cleaning
15. DataFrame Manipulation
16. Iteration
17. Reset Index
18. Concatenation
19. Merging DataFrames
20. Joining DataFrames
21. GroupBy Operations
22. Pivot Tables
23. Working with DateTime
24. Reading and Writing Files
25. Handling Large Datasets

## 1. Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Display settings for better readability
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 50)
pd.set_option('display.width', 100)

print(f"Pandas version  : {pd.__version__}")
print(f"NumPy  version  : {np.__version__}")
print("Libraries loaded successfully!")

Pandas version  : 2.3.3
NumPy  version  : 2.3.5
Libraries loaded successfully!

---
## 2. Introduction to Pandas

### What is Pandas?
**Pandas** (Panel Data) is an open-source Python library built on top of NumPy.  
It provides **fast, flexible, and expressive data structures** designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data both easy and intuitive.

### Core Functionality
| Feature | Description |
|---------|-------------|
| Data Loading | Read/write CSV, Excel, JSON, SQL, Parquet, etc. |
| Data Cleaning | Handle missing values, duplicates, type casting |
| Data Manipulation | Filter, sort, group, merge, reshape |
| Statistical Analysis | describe(), mean(), std(), corr() |
| Time Series | Datetime indexing, resampling, rolling windows |

### Key Data Structures
| Structure | Dimensions | Description |
|-----------|-----------|-------------|
| **Series** | 1D | Labeled array holding any data type |
| **DataFrame** | 2D | Table of rows × columns (most used) |

In [2]:
# Example: Plain Python vs Pandas
# ---- Plain Python ----
students = [("Alice", 85), ("Bob", 92), ("Charlie", 78)]
avg = sum(s[1] for s in students) / len(students)
print("Plain Python average:", avg)

# ---- Pandas way ----
df_students = pd.DataFrame(students, columns=["Name", "Score"])
print("\nPandas DataFrame:")
print(df_students)
print(f"\nMean Score (pandas): {df_students['Score'].mean()}")
print(f"Max  Score (pandas): {df_students['Score'].max()}")

Plain Python average: 85.0

Pandas DataFrame:
      Name  Score
0    Alice     85
1      Bob     92
2  Charlie     78

Mean Score (pandas): 85.0
Max  Score (pandas): 92

---
## 3. Characteristics of Pandas

| Characteristic | What it means |
|---------------|--------------|
| **Data Handling** | Reads/writes many file formats (CSV, Excel, JSON, SQL) |
| **Performance** | Vectorized operations — no need for slow Python for-loops |
| **Flexibility** | Supports mixed data types in the same DataFrame |
| **Integration** | Works seamlessly with NumPy, Scikit-learn, Matplotlib |
| **User-friendly API** | Intuitive syntax close to SQL / spreadsheet thinking |

In [3]:
# ── 1. Data Handling ──────────────────────────────────────────────
import io
csv_data = "Name,Age,Score\nAlice,25,88\nBob,30,92\nCharlie,22,75"
df_csv = pd.read_csv(io.StringIO(csv_data))
print("Data Handling — read from CSV-like string:")
print(df_csv)

Data Handling — read from CSV-like string:
      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   22     75

In [4]:
# ── 2. Performance — vectorized ops ──────────────────────────────
arr = np.random.randint(1, 100, size=1_000_000)
s = pd.Series(arr)
import time
t0 = time.time(); result = s * 2; t1 = time.time()
print(f"\nPerformance — multiply 1M elements: {(t1-t0)*1000:.2f} ms (vectorized)")

Performance — multiply 1M elements: 2.00 ms (vectorized)

In [5]:
# ── 3. Flexibility — mixed data types ────────────────────────────
df_flex = pd.DataFrame({
    "Name"  : ["Alice", "Bob"],
    "Age"   : [25, 30],
    "Score" : [88.5, 92.0],
    "Passed": [True, True]
})
print("\nFlexibility — mixed dtypes:")
print(df_flex.dtypes)

Flexibility — mixed dtypes:
Name       object
Age         int64
Score     float64
Passed       bool
dtype: object

In [6]:
# ── 4. Integration with NumPy ─────────────────────────────────────
np_array = np.array([[1, 2], [3, 4], [5, 6]])
df_np = pd.DataFrame(np_array, columns=["A", "B"])
print("\nIntegration — DataFrame from NumPy array:")
print(df_np)
print("Back to NumPy:", df_np.values)

Integration — DataFrame from NumPy array:
   A  B
0  1  2
1  3  4
2  5  6
Back to NumPy: [[1 2]
 [3 4]
 [5 6]]

In [7]:
# ── 5. User-friendly API ──────────────────────────────────────────
print("\nUser-friendly API — describe():")
print(df_csv.describe())

User-friendly API — describe():
             Age      Score
count   3.000000   3.000000
mean   25.666667  85.000000
std     4.041452   8.888194
min    22.000000  75.000000
25%    23.500000  81.500000
50%    25.000000  88.000000
75%    27.500000  90.000000
max    30.000000  92.000000

---
## 4. Series — 1D Labeled Array

### What is a Series?
A **Series** is a **one-dimensional labeled array** capable of holding any data type  
(integers, strings, floats, Python objects, etc.).

```
Index  →  Labels (default: 0, 1, 2 …)
Values →  The actual data
```

### Components of a Series
| Component | Description |
|-----------|-------------|
| `data`    | The array-like values |
| `index`   | Labels for each element (default RangeIndex) |
| `dtype`   | The data type of the values |
| `name`    | Optional name for the Series |

### Key Facts
- Default index is `0, 1, 2, …` (integer-based)
- Can hold **any Python data type**
- Supports **label-based access**: `s['label']`
- A DataFrame column is a Series

---
## 5. Creating a Series

In [8]:
# ── Series components ─────────────────────────────────────────────

s = pd.Series([10, 20, 30, 40, 50], name="Marks")

print("Series:\n", s)
print("\nIndex :", s.index.tolist())
print("\nValues:", s.values)
print("\ndtype :", s.dtype)
print("\nname  :", s.name)

Series:
 0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

Index : [0, 1, 2, 3, 4]

Values: [10 20 30 40 50]

dtype : int64

name  : Marks

In [9]:
# ── Create from list with default index ───────────────────────────
print("\n--- From list (default index) ---")

s1 = pd.Series([100, 200, 300, 400])
print(s1)

--- From list (default index) ---
0    100
1    200
2    300
3    400
dtype: int64

In [10]:
# ── Create from list with custom index ───────────────────────────
print("\n--- From list (custom index) ---")

s2 = pd.Series([100, 200, 300, 400], index=["a", "b", "c", "d"])
print(s2)
print("Access by label s2['b']:", s2["b"])

--- From list (custom index) ---
a    100
b    200
c    300
d    400
dtype: int64
Access by label s2['b']: 200

In [11]:
# ── Create from dictionary ────────────────────────────────────────
print("\n--- From dictionary (keys become index) ---")

marks_dict = {"Math": 90, "Science": 85, "English": 78, "History": 92}

s3 = pd.Series(marks_dict)
print(s3)
print("Access Science:", s3["Science"])

--- From dictionary (keys become index) ---
Math       90
Science    85
English    78
History    92
dtype: int64
Access Science: 85

In [12]:
# ── Create from scalar ────────────────────────────────────────────
print("\n--- From scalar (broadcasts to all index labels) ---")

s4 = pd.Series(5, index=["x", "y", "z"])
print(s4)

--- From scalar (broadcasts to all index labels) ---
x    5
y    5
z    5
dtype: int64

In [13]:
# ── Index alignment ───────────────────────────────────────────────
print("\n--- Index alignment example ---")

s_a = pd.Series({"Math": 90, "Science": 85, "English": 78})
s_b = pd.Series({"Math": 80, "Science": 95, "History": 70})
print("Sum (NaN where index doesn't match):\n", s_a + s_b)

--- Index alignment example ---
Sum (NaN where index doesn't match):
 English      NaN
History      NaN
Math       170.0
Science    180.0
dtype: float64

---
## 6. DataFrame — Introduction and Structure

### What is a DataFrame?
A **DataFrame** is a **2-dimensional labeled data structure** with columns of potentially different data types.  
Think of it as a spreadsheet, SQL table, or a dictionary of Series objects.

```
         Name   Age  Score
    0   Alice    25   88.5      ← Row (axis=0)
    1     Bob    30   92.0
    2  Charlie   22   75.0
    ↑
 Column (axis=1)
```

### Attributes of a DataFrame
| Attribute | Description |
|-----------|-------------|
| `df.shape`   | (rows, columns) |
| `df.dtypes`  | Data type of each column |
| `df.columns` | Column labels |
| `df.index`   | Row labels |
| `df.values`  | Pandas array of values |
| `df.info()`  | Summary of dtypes & non-null counts |
| `df.describe()` | Statistical summary |

In [14]:
df = pd.DataFrame({
    "Name" : ["Alice", "Bob", "Charlie", "Diana"],
    "Age"  : [25, 30, 22, 28],
    "Score": [88.5, 92.0, 75.0, 95.5],
    "City" : ["NY", "LA", "NY", "Chicago"]
})

print("DataFrame:\n", df)
print("\nshape   :", df.shape)
print("\ncolumns :", df.columns.tolist())
print("\nindex   :", df.index.tolist())
print("\ndtypes:\n", df.dtypes)
print("\ninfo():")
df.info()
print("\ndescribe():\n", df.describe())

DataFrame:
       Name  Age  Score     City
0    Alice   25   88.5       NY
1      Bob   30   92.0       LA
2  Charlie   22   75.0       NY
3    Diana   28   95.5  Chicago

shape   : (4, 4)

columns : ['Name', 'Age', 'Score', 'City']

index   : [0, 1, 2, 3]

dtypes:
 Name      object
Age        int64
Score    float64
City      object
dtype: object

info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      float64
 3   City    4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

describe():
          Age      Score
count   4.00   4.000000
mean   26.25  87.750000
std     3.50   8.967534
min    22.00  75.000000
25%    24.25  85.125000
50%    26.50  90.250000
75%    28.50  92.875000
max    30.00  95.500000

---
## 7. Properties of DataFrame

### 1. Heterogeneous Data — different dtypes in different columns
### 2. Size-Mutable — rows and columns can be added/removed
### 3. Labeled Axes — named rows and columns
### 4. Alignment — operations auto-align on index
### 5. Integration — interoperates with NumPy

In [15]:
# ── 1. Heterogeneous Data ─────────────────────────────────────────
df_hetero = pd.DataFrame({
    "Name"   : ["Alice", "Bob"],     # object (string)
    "Age"    : [25, 30],             # int64
    "Score"  : [88.5, 92.0],         # float64
    "Passed" : [True, True]          # bool
})
print("1. Heterogeneous Data:")
print(df_hetero.dtypes, "\n")

1. Heterogeneous Data:
Name       object
Age         int64
Score     float64
Passed       bool
dtype: object

In [16]:
# ── 2. Size-Mutable ───────────────────────────────────────────────
df_mut = df_hetero.copy()

df_mut["Grade"] = ["A", "A+"]         # add column
print("2. Size-Mutable — after adding 'Grade' column:")
print(df_mut)

df_mut = df_mut.drop(columns=["Grade"])  # Drop
print("   After removing 'Grade':", df_mut.columns.tolist(), "\n")

2. Size-Mutable — after adding 'Grade' column:
    Name  Age  Score  Passed Grade
0  Alice   25   88.5    True     A
1    Bob   30   92.0    True    A+
   After removing 'Grade': ['Name', 'Age', 'Score', 'Passed']

In [17]:
# ── 3. Labeled Axes ───────────────────────────────────────────────
df_labeled = pd.DataFrame(
    {"Math": [90, 85], "Science": [78, 92]},
    index=["Alice", "Bob"]
)
print("3. Labeled Axes (custom row index):")
print(df_labeled, "\n")

3. Labeled Axes (custom row index):
       Math  Science
Alice    90       78
Bob      85       92

In [18]:
# ── 4. Alignment ──────────────────────────────────────────────────
s1 = pd.Series({"Math": 10, "Science": 20, "English": 30})
s2 = pd.Series({"Math":  5, "Science": 15, "History": 25})
print("4. Alignment — adding two Series with different indices:")
print(s1 + s2, "\n")   # NaN where indices don't overlap

4. Alignment — adding two Series with different indices:
English     NaN
History     NaN
Math       15.0
Science    35.0
dtype: float64

In [19]:
# ── 5. Integration with NumPy ─────────────────────────────────────
df_int = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
print("5. Integration — applying np.sqrt on DataFrame values:")
print(np.sqrt(df_int))

5. Integration — applying np.sqrt on DataFrame values:
          A         B
0  1.000000  2.000000
1  1.414214  2.236068
2  1.732051  2.449490

---
## 8. Creating a DataFrame

Three common ways:
1. **List of Lists** — specify column names explicitly
2. **List of Dictionaries** — keys become column names
3. **Dictionary of Series** — index alignment is automatic

In [20]:
# ── Method 1: List of Lists ───────────────────────────────────────
data_lol = [
    ["Alice",   25, 88.5],
    ["Bob",     30, 92.0],
    ["Charlie", 22, 75.0],
    ["Diana",   28, 95.5],
]

df1 = pd.DataFrame(data_lol, columns=["Name", "Age", "Score"])
print("Method 1 — List of Lists:")
print(df1)

Method 1 — List of Lists:
      Name  Age  Score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   22   75.0
3    Diana   28   95.5

In [21]:
# ── Method 2: List of Dictionaries ───────────────────────────────
data_lod = [
    {"Name": "Alice",   "Age": 25, "Score": 88.5},
    {"Name": "Bob",     "Age": 30, "Score": 92.0},
    {"Name": "Charlie", "Age": 22, "Score": 75.0},
    {"Name": "Diana",   "Age": 28},                # missing Score → NaN
]

df2 = pd.DataFrame(data_lod)
print("\nMethod 2 — List of Dictionaries (note NaN for Diana's Score):")
print(df2)

Method 2 — List of Dictionaries (note NaN for Diana's Score):
      Name  Age  Score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   22   75.0
3    Diana   28    NaN

In [22]:
# ── Method 3: Dictionary of Series ───────────────────────────────
names  = pd.Series(["Alice", "Bob", "Charlie", "Diana"])
ages   = pd.Series([25, 30, 22, 28])
scores = pd.Series([88.5, 92.0, 75.0, 95.5])

df3 = pd.DataFrame({"Name": names, "Age": ages, "Score": scores})
print("\nMethod 3 — Dictionary of Series:")
print(df3)

Method 3 — Dictionary of Series:
      Name  Age  Score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   22   75.0
3    Diana   28   95.5

In [23]:
# Index alignment demo with Series
s_a = pd.Series([1, 2, 3], index=[0, 1, 2])
s_b = pd.Series([10, 20],  index=[0, 1])      # shorter series
df_align = pd.DataFrame({"A": s_a, "B": s_b})
print("\nIndex alignment — shorter Series gets NaN:")
print(df_align)

Index alignment — shorter Series gets NaN:
   A     B
0  1  10.0
1  2  20.0
2  3   NaN

---
## 9. Adding Columns to a DataFrame

| Method | Description |
|--------|-------------|
| `df['new_col'] = scalar` | Broadcasts one value to all rows |
| `df['new_col'] = list/Series` | Assigns element-wise |
| `df.assign(col=...)` | Returns a new DataFrame (chainable) |

In [24]:
df_add = pd.DataFrame({
    "Name" : ["Alice", "Bob", "Charlie", "Diana"],
    "Score": [88.5, 92.0, 75.0, 95.5]
})

# ── Assign scalar value (broadcasts to all rows) ──────────────────
df_add["Country"] = "India"
print("After scalar assignment (Country = India):")
print(df_add)

After scalar assignment (Country = India):
      Name  Score Country
0    Alice   88.5   India
1      Bob   92.0   India
2  Charlie   75.0   India
3    Diana   95.5   India

In [25]:
# ── Assign a list ─────────────────────────────────────────────────

df_add["Grade"] = ["A", "A+", "B+", "A+"]

print("\nAfter list assignment (Grade):")
print(df_add)

After list assignment (Grade):
      Name  Score Country Grade
0    Alice   88.5   India     A
1      Bob   92.0   India    A+
2  Charlie   75.0   India    B+
3    Diana   95.5   India    A+

In [26]:
# ── Assign a Series (index-aligned) ──────────────────────────────

bonus = pd.Series([5.0, 3.0, 7.0, 2.0], index=[0, 1, 2, 3])
df_add["Bonus"] = bonus
print("\nAfter Series assignment (Bonus):")
print(df_add)

After Series assignment (Bonus):
      Name  Score Country Grade  Bonus
0    Alice   88.5   India     A    5.0
1      Bob   92.0   India    A+    3.0
2  Charlie   75.0   India    B+    7.0
3    Diana   95.5   India    A+    2.0

In [27]:
# ── Using assign() — returns new DataFrame ────────────────────────

df_new = df_add.assign(
    FinalScore = df_add["Score"] + df_add["Bonus"],
    Passed     = lambda x: x["FinalScore"] >= 80
)
print("\nUsing assign() — chained column creation:")
print(df_new)

Using assign() — chained column creation:
      Name  Score Country Grade  Bonus  FinalScore  Passed
0    Alice   88.5   India     A    5.0        93.5    True
1      Bob   92.0   India    A+    3.0        95.0    True
2  Charlie   75.0   India    B+    7.0        82.0    True
3    Diana   95.5   India    A+    2.0        97.5    True

---
## 10. Renaming Columns — `rename()`

**Syntax:** `df.rename(columns={old: new}, inplace=False)`

| Parameter | Description |
|-----------|-------------|
| `columns` | Dict mapping old names → new names |
| `index`   | Dict mapping old row labels → new labels |
| `inplace` | `True` = modify in place; `False` (default) = return new DataFrame |

In [28]:
df_ren = pd.DataFrame({
    "nm" : ["Alice", "Bob", "Charlie"],
    "ag" : [25, 30, 22],
    "sc" : [88.5, 92.0, 75.0],
    "ct" : ["NY", "LA", "Chicago"]
})
print("Original columns:", df_ren.columns.tolist())

# ── Rename single column (returns new df) ─────────────────────────
df_r1 = df_ren.rename(columns={"nm": "Name"})
print("\nRename single column 'nm' → 'Name':")
print(df_r1.columns.tolist())

Original columns: ['nm', 'ag', 'sc', 'ct']

Rename single column 'nm' → 'Name':
['Name', 'ag', 'sc', 'ct']

In [29]:
# ── Rename multiple columns ───────────────────────────────────────
df_r2 = df_ren.rename(columns={"nm": "Name", "ag": "Age",
                                "sc": "Score", "ct": "City"})
print("\nRename multiple columns:")
print(df_r2)

Rename multiple columns:
      Name  Age  Score     City
0    Alice   25   88.5       NY
1      Bob   30   92.0       LA
2  Charlie   22   75.0  Chicago

In [30]:
# ── inplace=True ──────────────────────────────────────────────────
df_r3 = df_ren.copy()
df_r3.rename(columns={"nm": "Name", "ag": "Age"}, inplace=True)
print("\nAfter inplace=True rename:")
print(df_r3.columns.tolist())

After inplace=True rename:
['Name', 'Age', 'sc', 'ct']

---
## 11. Indexing and Data Selection

### Types of Indexing
| Indexer | Basis | Usage |
|---------|-------|-------|
| `loc`   | **Label-based** | Use actual row/column names |
| `iloc`  | **Position-based** | Use integer positions (0-based) |

> **Rule of Thumb:** Use `loc` when you know the label. Use `iloc` when you know the position.

---
### `loc` — Label-Based Indexing

In [31]:
df_idx = pd.DataFrame({
    "Name"  : ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Age"   : [25, 30, 22, 28, 35],
    "Score" : [88.5, 92.0, 75.0, 95.5, 80.0],
    "City"  : ["NY", "LA", "NY", "Chicago", "NY"],
    "Dept"  : ["DS", "ML", "DS", "AI", "ML"]
}, index=["r0", "r1", "r2", "r3", "r4"])

print("DataFrame with custom index:\n", df_idx)

DataFrame with custom index:
        Name  Age  Score     City Dept
r0    Alice   25   88.5       NY   DS
r1      Bob   30   92.0       LA   ML
r2  Charlie   22   75.0       NY   DS
r3    Diana   28   95.5  Chicago   AI
r4      Eve   35   80.0       NY   ML

In [32]:
# ── loc: Access single row ────────────────────────────────────────
print("\n--- loc: Access single row 'r1' ---")
print(df_idx.loc["r1"])

# ── loc: Access single column ────────────────────────────────────
print("\n--- loc: Access single column 'Score' ---")
print(df_idx.loc[:, "Score"])

--- loc: Access single row 'r1' ---
Name      Bob
Age        30
Score    92.0
City       LA
Dept       ML
Name: r1, dtype: object

--- loc: Access single column 'Score' ---
r0    88.5
r1    92.0
r2    75.0
r3    95.5
r4    80.0
Name: Score, dtype: float64

In [33]:
# ── loc: Access multiple rows & columns ──────────────────────────
print("\n--- loc: Multiple rows ['r0','r2'] & columns ['Name','Score'] ---")
print(df_idx.loc[["r0", "r2"], ["Name", "Score"]])

--- loc: Multiple rows ['r0','r2'] & columns ['Name','Score'] ---
       Name  Score
r0    Alice   88.5
r2  Charlie   75.0

In [34]:
# ── loc: Slice of rows ────────────────────────────────────────────

print("\n--- loc: Row slice r1 to r3 ---")
print(df_idx.loc["r1":"r3"])

--- loc: Row slice r1 to r3 ---
       Name  Age  Score     City Dept
r1      Bob   30   92.0       LA   ML
r2  Charlie   22   75.0       NY   DS
r3    Diana   28   95.5  Chicago   AI

In [35]:
# ── loc: Conditional (boolean) selection ─────────────────────────
print("\n--- loc: Score > 85 ---")
print(df_idx.loc[df_idx["Score"] > 85])

print("\n--- loc: Score > 80 AND City == 'NY' ---")
print(df_idx.loc[(df_idx["Score"] > 80) & (df_idx["City"] == "NY")])

--- loc: Score > 85 ---
     Name  Age  Score     City Dept
r0  Alice   25   88.5       NY   DS
r1    Bob   30   92.0       LA   ML
r3  Diana   28   95.5  Chicago   AI

--- loc: Score > 80 AND City == 'NY' ---
     Name  Age  Score City Dept
r0  Alice   25   88.5   NY   DS

### `iloc` — Position-Based Indexing

In [36]:
# ── iloc: Access single row by position ──────────────────────────
print("--- iloc: Single row at position 0 ---")
print(df_idx.iloc[0])

print("\n--- iloc: Single row at position -1 (last row) ---")
print(df_idx.iloc[-1])

# ── iloc: Access single column by position ────────────────────────
print("\n--- iloc: Column at position 2 (Score) ---")
print(df_idx.iloc[:, 2])

--- iloc: Single row at position 0 ---
Name     Alice
Age         25
Score     88.5
City        NY
Dept        DS
Name: r0, dtype: object

--- iloc: Single row at position -1 (last row) ---
Name      Eve
Age        35
Score    80.0
City       NY
Dept       ML
Name: r4, dtype: object

--- iloc: Column at position 2 (Score) ---
r0    88.5
r1    92.0
r2    75.0
r3    95.5
r4    80.0
Name: Score, dtype: float64

In [37]:
# ── iloc: Subset of rows and columns ─────────────────────────────
print("\n--- iloc: Rows 0-2, Columns 0-2 ---")
print(df_idx.iloc[0:3, 0:3])

print("\n--- iloc: Every other row, first 3 columns ---")
print(df_idx.iloc[::2, :3])

print("\n--- iloc: Specific rows [0,2,4] and columns [0,2] ---")
print(df_idx.iloc[[0, 2, 4], [0, 2]])

--- iloc: Rows 0-2, Columns 0-2 ---
       Name  Age  Score
r0    Alice   25   88.5
r1      Bob   30   92.0
r2  Charlie   22   75.0

--- iloc: Every other row, first 3 columns ---
       Name  Age  Score
r0    Alice   25   88.5
r2  Charlie   22   75.0
r4      Eve   35   80.0

--- iloc: Specific rows [0,2,4] and columns [0,2] ---
       Name  Score
r0    Alice   88.5
r2  Charlie   75.0
r4      Eve   80.0

---
## 12. DataFrame Slicing

### Types of Slicing
| Type | Description |
|------|-------------|
| Row slicing | Select a range of rows |
| Column slicing | Select specific columns by label or position |
| Combined slicing | Select both rows and columns simultaneously |

In [38]:
df_sl = pd.DataFrame({
    "Name"  : ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Age"   : [25, 30, 22, 28, 35],
    "Score" : [88.5, 92.0, 75.0, 95.5, 80.0],
    "City"  : ["NY", "LA", "NY", "Chicago", "NY"],
    "Dept"  : ["DS", "ML", "DS", "AI", "ML"]
})
print("Original DataFrame:\n", df_sl)

Original DataFrame:
       Name  Age  Score     City Dept
0    Alice   25   88.5       NY   DS
1      Bob   30   92.0       LA   ML
2  Charlie   22   75.0       NY   DS
3    Diana   28   95.5  Chicago   AI
4      Eve   35   80.0       NY   ML

In [39]:
# ── Row slicing ───────────────────────────────────────────────────
print("\n--- Row slicing: rows 1 to 3 (iloc) ---")
print(df_sl.iloc[1:4])

--- Row slicing: rows 1 to 3 (iloc) ---
      Name  Age  Score     City Dept
1      Bob   30   92.0       LA   ML
2  Charlie   22   75.0       NY   DS
3    Diana   28   95.5  Chicago   AI

In [40]:
# ── Column slicing — label-based ──────────────────────────────────
print("\n--- Column slicing (label-based): Name and Score ---")
print(df_sl[["Name", "Score"]])

# ── Column slicing — position-based ──────────────────────────────
print("\n--- Column slicing (position-based): columns 0,1,2 ---")
print(df_sl.iloc[:, 0:3])

--- Column slicing (label-based): Name and Score ---
      Name  Score
0    Alice   88.5
1      Bob   92.0
2  Charlie   75.0
3    Diana   95.5
4      Eve   80.0

--- Column slicing (position-based): columns 0,1,2 ---
      Name  Age  Score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   22   75.0
3    Diana   28   95.5
4      Eve   35   80.0

In [41]:
# ── Combined slicing — loc (label-based) ─────────────────────────
print("\n--- Combined slicing (loc — label-based rows+cols): rows 1-3, Name/Score/City ---")
print(df_sl.loc[1:3, ["Name", "Score", "City"]])

# ── Combined slicing — iloc (position-based) ─────────────────────
print("\n--- Combined slicing (iloc — position-based): rows 0-2, cols 0,2,3 ---")
print(df_sl.iloc[0:3, [0, 2, 3]])

--- Combined slicing (loc — label-based rows+cols): rows 1-3, Name/Score/City ---
      Name  Score     City
1      Bob   92.0       LA
2  Charlie   75.0       NY
3    Diana   95.5  Chicago

--- Combined slicing (iloc — position-based): rows 0-2, cols 0,2,3 ---
      Name  Score City
0    Alice   88.5   NY
1      Bob   92.0   LA
2  Charlie   75.0   NY

---
## 13. `set_index` and Hierarchical Indexing

### Characteristics of `set_index`
| Feature | Description |
|---------|-------------|
| **Custom indexing** | Replace default RangeIndex with a column |
| **Hierarchical indexing** | Pass a list of columns to create a MultiIndex |
| **In-place operation** | Use `inplace=True` to modify without reassignment |

In [42]:
df_si = pd.DataFrame({
    "Name"  : ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Dept"  : ["DS", "ML", "DS", "AI", "ML"],
    "City"  : ["NY", "LA", "NY", "Chicago", "NY"],
    "Score" : [88.5, 92.0, 75.0, 95.5, 80.0]
})
print("Original:\n", df_si)

Original:
       Name Dept     City  Score
0    Alice   DS       NY   88.5
1      Bob   ML       LA   92.0
2  Charlie   DS       NY   75.0
3    Diana   AI  Chicago   95.5
4      Eve   ML       NY   80.0

In [43]:
# ── Custom indexing (single column) ──────────────────────────────
df_name_idx = df_si.set_index("Name")

print("\nCustom indexing — set_index('Name'):")
print(df_name_idx)
print("Access Alice:", df_name_idx.loc["Alice"])

Custom indexing — set_index('Name'):
        Dept     City  Score
Name
Alice     DS       NY   88.5
Bob       ML       LA   92.0
Charlie   DS       NY   75.0
Diana     AI  Chicago   95.5
Eve       ML       NY   80.0
Access Alice: Dept       DS
City       NY
Score    88.5
Name: Alice, dtype: object

In [44]:
# ── Hierarchical (MultiIndex) ─────────────────────────────────────

df_multi = df_si.set_index(["Dept", "Name"])
print("\nHierarchical indexing — set_index(['Dept','Name']):")
print(df_multi)
print("\nAccess Dept='DS':", df_multi.loc["DS"])
print("\nAccess DS/Charlie:", df_multi.loc[("DS", "Charlie")])

Hierarchical indexing — set_index(['Dept','Name']):
                 City  Score
Dept Name
DS   Alice         NY   88.5
ML   Bob           LA   92.0
DS   Charlie       NY   75.0
AI   Diana    Chicago   95.5
ML   Eve           NY   80.0

Access Dept='DS':         City  Score
Name
Alice     NY   88.5
Charlie   NY   75.0

Access DS/Charlie: City       NY
Score    75.0
Name: (DS, Charlie), dtype: object

In [45]:
# ── in-place operation ────────────────────────────────────────────
df_inplace = df_si.copy()
df_inplace.set_index("Name", inplace=True)
print("\ninplace=True — original variable is modified:")
print(df_inplace.head())

inplace=True — original variable is modified:
        Dept     City  Score
Name
Alice     DS       NY   88.5
Bob       ML       LA   92.0
Charlie   DS       NY   75.0
Diana     AI  Chicago   95.5
Eve       ML       NY   80.0

---
## 14. Data Cleaning

### Topics Covered
1. Handling missing data — `isnull()`, `dropna()`, `fillna()`
2. Data type conversion — `astype()`
3. Rename rows
4. Handle duplicates — `drop_duplicates()`
5. String operations — `str` accessor

In [46]:
df_clean = pd.DataFrame({
    "Name"  : ["Alice", "Bob", None, "Diana", "Eve", "Bob"],
    "Age"   : [25, np.nan, 22, 28, 35, 30],
    "Score" : [88.5, 92.0, np.nan, 95.5, np.nan, 92.0],
    "City"  : ["NY", "LA", "NY", None, "NY", "LA"],
    "Grade" : ["  A  ", "  A+ ", "  B+ ", "  A+ ", "  B  ", "  A+ "]
})

print("DataFrame with missing values:\n", df_clean)

DataFrame with missing values:
     Name   Age  Score  City  Grade
0  Alice  25.0   88.5    NY    A
1    Bob   NaN   92.0    LA    A+
2   None  22.0    NaN    NY    B+
3  Diana  28.0   95.5  None    A+
4    Eve  35.0    NaN    NY    B
5    Bob  30.0   92.0    LA    A+

In [47]:
# ── isnull() / notnull() ──────────────────────────────────────────

print("\nisnull():\n", df_clean.isnull())
print("\nMissing value count per column:\n", df_clean.isnull().sum())

isnull():
     Name    Age  Score   City  Grade
0  False  False  False  False  False
1  False   True  False  False  False
2   True  False   True  False  False
3  False  False  False   True  False
4  False  False   True  False  False
5  False  False  False  False  False

Missing value count per column:
 Name     1
Age      1
Score    2
City     1
Grade    0
dtype: int64

In [48]:
# ── dropna() ─────────────────────────────────────────────────────
print("\ndropna() — drop rows with ANY missing value:")
print(df_clean.dropna())

print("\ndropna(axis=1) — drop COLUMNS with any missing value:")
print(df_clean.dropna(axis=1))

print("\ndropna(thresh=4) — keep rows with at least 4 non-null values:")
print(df_clean.dropna(thresh=4))

dropna() — drop rows with ANY missing value:
    Name   Age  Score City  Grade
0  Alice  25.0   88.5   NY    A
5    Bob  30.0   92.0   LA    A+

dropna(axis=1) — drop COLUMNS with any missing value:
   Grade
0    A
1    A+
2    B+
3    A+
4    B
5    A+

dropna(thresh=4) — keep rows with at least 4 non-null values:
    Name   Age  Score  City  Grade
0  Alice  25.0   88.5    NY    A
1    Bob   NaN   92.0    LA    A+
3  Diana  28.0   95.5  None    A+
4    Eve  35.0    NaN    NY    B
5    Bob  30.0   92.0    LA    A+

In [49]:
# ── fillna() ─────────────────────────────────────────────────────
print("\nfillna(0) — fill all NaN with 0:")
print(df_clean.fillna(0))

print("\nfillna(method='ffill') — forward fill:")
print(df_clean.fillna(method='ffill'))

print("\nfillna(method='bfill') — backward fill:")
print(df_clean.fillna(method='bfill'))

print("\nfillna per-column dict:")
print(df_clean.fillna({"Age": df_clean["Age"].mean(), "Score": 0, "City": "Unknown"}))

fillna(0) — fill all NaN with 0:
    Name   Age  Score City  Grade
0  Alice  25.0   88.5   NY    A
1    Bob   0.0   92.0   LA    A+
2      0  22.0    0.0   NY    B+
3  Diana  28.0   95.5    0    A+
4    Eve  35.0    0.0   NY    B
5    Bob  30.0   92.0   LA    A+

fillna(method='ffill') — forward fill:
    Name   Age  Score City  Grade
0  Alice  25.0   88.5   NY    A
1    Bob  25.0   92.0   LA    A+
2    Bob  22.0   92.0   NY    B+
3  Diana  28.0   95.5   NY    A+
4    Eve  35.0   95.5   NY    B
5    Bob  30.0   92.0   LA    A+

fillna(method='bfill') — backward fill:
    Name   Age  Score City  Grade
0  Alice  25.0   88.5   NY    A
1    Bob  22.0   92.0   LA    A+
2  Diana  22.0   95.5   NY    B+
3  Diana  28.0   95.5   NY    A+
4    Eve  35.0   92.0   NY    B
5    Bob  30.0   92.0   LA    A+

fillna per-column dict:
    Name   Age  Score     City  Grade
0  Alice  25.0   88.5       NY    A
1    Bob  28.0   92.0       LA    A+
2   None  22.0    0.0       NY    B+
3  Diana  28.0   95.5  Unknown    A+
4    Eve  35.0    0.0       NY    B
5    Bob  30.0   92.0       LA    A+

In [50]:
df_c2 = pd.DataFrame({
    "Name"  : ["Alice", "Bob", "Bob", "Diana", "Alice"],
    "Age"   : ["25", "30", "30", "28", "25"],
    "Score" : [88.5, 92.0, 92.0, 95.5, 88.5],
    "Grade" : ["  A  ", "  A+  ", "  A+  ", "  A+  ", "  A  "]
})

# ── astype() — data type conversion ──────────────────────────────
print("dtypes before:\n", df_c2.dtypes)
df_c2["Age"] = df_c2["Age"].astype(int)

print("\nAfter Age astype(int):", df_c2["Age"].dtype)
df_c2["Score"] = df_c2["Score"].astype(float)
df_c2["Name"]  = df_c2["Name"].astype("category")
print("After Name astype('category'):", df_c2["Name"].dtype)

dtypes before:
 Name      object
Age       object
Score    float64
Grade     object
dtype: object

After Age astype(int): int64
After Name astype('category'): category

In [51]:
# ── Rename rows ───────────────────────────────────────────────────

df_row = df_c2.copy()
df_row = df_row.rename(index={0: "r0", 1: "r1", 2: "r2", 3: "r3", 4: "r4"})
print("\nRename rows:\n", df_row.index.tolist())

Rename rows:
 ['r0', 'r1', 'r2', 'r3', 'r4']

In [52]:
# ── drop_duplicates() ────────────────────────────────────────────

print("\nOriginal (with duplicates):\n", df_c2[["Name","Age","Score"]])
print("\ndrop_duplicates() — keep first:")
print(df_c2.drop_duplicates())
print("\ndrop_duplicates(subset=['Name']) — based on Name only:")
print(df_c2.drop_duplicates(subset=["Name"]))
print("\ndrop_duplicates(keep='last'):")
print(df_c2.drop_duplicates(keep="last"))

Original (with duplicates):
     Name  Age  Score
0  Alice   25   88.5
1    Bob   30   92.0
2    Bob   30   92.0
3  Diana   28   95.5
4  Alice   25   88.5

drop_duplicates() — keep first:
    Name  Age  Score   Grade
0  Alice   25   88.5     A
1    Bob   30   92.0    A+
3  Diana   28   95.5    A+

drop_duplicates(subset=['Name']) — based on Name only:
    Name  Age  Score   Grade
0  Alice   25   88.5     A
1    Bob   30   92.0    A+
3  Diana   28   95.5    A+

drop_duplicates(keep='last'):
    Name  Age  Score   Grade
2    Bob   30   92.0    A+
3  Diana   28   95.5    A+
4  Alice   25   88.5     A

In [53]:
# ── str accessor ──────────────────────────────────────────────────

df_c2["Grade"] = df_c2["Grade"].astype(str)

print("\nstr.strip() — remove whitespace:")
print(df_c2["Grade"].str.strip())
print("\nstr.upper():", df_c2["Name"].astype(str).str.upper().tolist())
print("str.lower():", df_c2["Name"].astype(str).str.lower().tolist())
print("str.contains('A'):", df_c2["Name"].astype(str).str.contains("A").tolist())
print("str.replace('A','@'):", df_c2["Name"].astype(str).str.replace("A", "@").tolist())
print("str.len():", df_c2["Name"].astype(str).str.len().tolist())
print("str.split() on 'Alice Bob':", pd.Series(["Alice Bob", "Charlie D"]).str.split())

str.strip() — remove whitespace:
0     A
1    A+
2    A+
3    A+
4     A
Name: Grade, dtype: object

str.upper(): ['ALICE', 'BOB', 'BOB', 'DIANA', 'ALICE']
str.lower(): ['alice', 'bob', 'bob', 'diana', 'alice']
str.contains('A'): [True, False, False, False, True]
str.replace('A','@'): ['@lice', 'Bob', 'Bob', 'Diana', '@lice']
str.len(): [5, 3, 3, 5, 5]
str.split() on 'Alice Bob': 0    [Alice, Bob]
1    [Charlie, D]
dtype: object

---
## 15. DataFrame Manipulation

### Topics
- Filtering rows (AND / OR / NOT)
- Sorting — `sort_values()`, `sort_index()`
- Adding computed columns
- Dropping columns / rows
- Mapping & applying functions — `map()`, `apply()`, `applymap()`

In [54]:
df_manip = pd.DataFrame({
    "Name"  : ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"],
    "Dept"  : ["DS", "ML", "DS", "AI", "ML", "DS"],
    "Age"   : [25, 30, 22, 28, 35, 27],
    "Score" : [88.5, 92.0, 75.0, 95.5, 80.0, 70.0],
    "City"  : ["NY", "LA", "NY", "Chicago", "NY", "LA"]
})

print("Base DataFrame:\n", df_manip)

# ── Filtering: Single condition ───────────────────────────────────

print("\n--- Filter: Score > 80 ---")
print(df_manip[df_manip["Score"] > 80])

Base DataFrame:
       Name Dept  Age  Score     City
0    Alice   DS   25   88.5       NY
1      Bob   ML   30   92.0       LA
2  Charlie   DS   22   75.0       NY
3    Diana   AI   28   95.5  Chicago
4      Eve   ML   35   80.0       NY
5    Frank   DS   27   70.0       LA

--- Filter: Score > 80 ---
    Name Dept  Age  Score     City
0  Alice   DS   25   88.5       NY
1    Bob   ML   30   92.0       LA
3  Diana   AI   28   95.5  Chicago

In [55]:
# ── Filtering: AND (&) ────────────────────────────────────────────

print("\n--- Filter: Score > 80 AND Dept == 'DS' ---")
print(df_manip[(df_manip["Score"] > 80) & (df_manip["Dept"] == "DS")])

--- Filter: Score > 80 AND Dept == 'DS' ---
    Name Dept  Age  Score City
0  Alice   DS   25   88.5   NY

In [56]:
# ── Filtering: OR (|) ─────────────────────────────────────────────

print("\n--- Filter: Dept == 'ML' OR City == 'Chicago' ---")
print(df_manip[(df_manip["Dept"] == "ML") | (df_manip["City"] == "Chicago")])

--- Filter: Dept == 'ML' OR City == 'Chicago' ---
    Name Dept  Age  Score     City
1    Bob   ML   30   92.0       LA
3  Diana   AI   28   95.5  Chicago
4    Eve   ML   35   80.0       NY

In [57]:
# ── Filtering: NOT (~) ────────────────────────────────────────────
print("\n--- Filter: NOT Dept == 'DS' ---")
print(df_manip[~(df_manip["Dept"] == "DS")])

--- Filter: NOT Dept == 'DS' ---
    Name Dept  Age  Score     City
1    Bob   ML   30   92.0       LA
3  Diana   AI   28   95.5  Chicago
4    Eve   ML   35   80.0       NY

In [58]:
# ── sort_values() ────────────────────────────────────────────────
print("--- sort_values(by='Score', ascending=False) ---")
print(df_manip.sort_values(by="Score", ascending=False))

print("\n--- sort_values(by=['Dept','Score'], ascending=[True,False]) ---")
print(df_manip.sort_values(by=["Dept", "Score"], ascending=[True, False]))

print("\n--- sort_values with na_position='first' ---")
df_with_nan = df_manip.copy()
df_with_nan.loc[0, "Score"] = np.nan
print(df_with_nan.sort_values("Score", na_position="first"))

--- sort_values(by='Score', ascending=False) ---
      Name Dept  Age  Score     City
3    Diana   AI   28   95.5  Chicago
1      Bob   ML   30   92.0       LA
0    Alice   DS   25   88.5       NY
4      Eve   ML   35   80.0       NY
2  Charlie   DS   22   75.0       NY
5    Frank   DS   27   70.0       LA

--- sort_values(by=['Dept','Score'], ascending=[True,False]) ---
      Name Dept  Age  Score     City
3    Diana   AI   28   95.5  Chicago
0    Alice   DS   25   88.5       NY
2  Charlie   DS   22   75.0       NY
5    Frank   DS   27   70.0       LA
1      Bob   ML   30   92.0       LA
4      Eve   ML   35   80.0       NY

--- sort_values with na_position='first' ---
      Name Dept  Age  Score     City
0    Alice   DS   25    NaN       NY
5    Frank   DS   27   70.0       LA
2  Charlie   DS   22   75.0       NY
4      Eve   ML   35   80.0       NY
1      Bob   ML   30   92.0       LA
3    Diana   AI   28   95.5  Chicago

In [59]:
# ── sort_index() ─────────────────────────────────────────────────
df_shuffled = df_manip.sample(frac=1, random_state=42)
print("\n--- sort_index() — restore original row order ---")
print(df_shuffled.sort_index())

print("\n--- sort_index(axis=1) — sort columns alphabetically ---")
print(df_manip.sort_index(axis=1))

--- sort_index() — restore original row order ---
      Name Dept  Age  Score     City
0    Alice   DS   25   88.5       NY
1      Bob   ML   30   92.0       LA
2  Charlie   DS   22   75.0       NY
3    Diana   AI   28   95.5  Chicago
4      Eve   ML   35   80.0       NY
5    Frank   DS   27   70.0       LA

--- sort_index(axis=1) — sort columns alphabetically ---
   Age     City Dept     Name  Score
0   25       NY   DS    Alice   88.5
1   30       LA   ML      Bob   92.0
2   22       NY   DS  Charlie   75.0
3   28  Chicago   AI    Diana   95.5
4   35       NY   ML      Eve   80.0
5   27       LA   DS    Frank   70.0

In [60]:
# ── Adding computed columns ───────────────────────────────────────

df_m2 = df_manip.copy()
df_m2["ScoreBonus"] = df_m2["Score"] + 5
df_m2["AgeGroup"]   = df_m2["Age"].apply(lambda x: "Junior" if x < 28 else "Senior")
print("After adding ScoreBonus and AgeGroup:\n", df_m2)

After adding ScoreBonus and AgeGroup:
       Name Dept  Age  Score     City  ScoreBonus AgeGroup
0    Alice   DS   25   88.5       NY        93.5   Junior
1      Bob   ML   30   92.0       LA        97.0   Senior
2  Charlie   DS   22   75.0       NY        80.0   Junior
3    Diana   AI   28   95.5  Chicago       100.5   Senior
4      Eve   ML   35   80.0       NY        85.0   Senior
5    Frank   DS   27   70.0       LA        75.0   Junior

In [61]:
# ── drop() — remove columns ───────────────────────────────────────
df_drop = df_m2.drop(columns=["ScoreBonus"])
print("\nAfter drop(columns=['ScoreBonus']):", df_drop.columns.tolist())

df_drop2 = df_m2.drop(columns=["ScoreBonus", "AgeGroup"])
print("After drop multiple columns:", df_drop2.columns.tolist())

After drop(columns=['ScoreBonus']): ['Name', 'Dept', 'Age', 'Score', 'City', 'AgeGroup']
After drop multiple columns: ['Name', 'Dept', 'Age', 'Score', 'City']

In [62]:
# ── drop() — remove rows ──────────────────────────────────────────

df_drop_rows = df_manip.drop(index=[0, 2])
print("\nAfter drop rows [0,2]:\n", df_drop_rows)

After drop rows [0,2]:
     Name Dept  Age  Score     City
1    Bob   ML   30   92.0       LA
3  Diana   AI   28   95.5  Chicago
4    Eve   ML   35   80.0       NY
5  Frank   DS   27   70.0       LA

In [63]:
# ── map() — element-wise value substitution on a Series ──────────

df_fn = df_manip.copy()
dept_map = {"DS": "Data Science", "ML": "Machine Learning", "AI": "Artificial Intelligence"}
df_fn["DeptFull"] = df_fn["Dept"].map(dept_map)
print("map() — expand Dept codes:\n", df_fn[["Name","Dept","DeptFull"]])

map() — expand Dept codes:
       Name Dept                 DeptFull
0    Alice   DS             Data Science
1      Bob   ML         Machine Learning
2  Charlie   DS             Data Science
3    Diana   AI  Artificial Intelligence
4      Eve   ML         Machine Learning
5    Frank   DS             Data Science

In [64]:
# ── map() with a function ────────────────────────────────────────

df_fn["Grade"] = df_fn["Score"].map(lambda x: "A" if x >= 90 else ("B" if x >= 75 else "C"))
print("\nmap() with lambda — Grade:\n", df_fn[["Name","Score","Grade"]])

map() with lambda — Grade:
       Name  Score Grade
0    Alice   88.5     B
1      Bob   92.0     A
2  Charlie   75.0     B
3    Diana   95.5     A
4      Eve   80.0     B
5    Frank   70.0     C

In [65]:
# ── apply() on a Series ───────────────────────────────────────────
print("\napply() on Score Series — add 10:")
print(df_fn["Score"].apply(lambda x: x + 10))

apply() on Score Series — add 10:
0     98.5
1    102.0
2     85.0
3    105.5
4     90.0
5     80.0
Name: Score, dtype: float64

In [66]:
# ── apply() on DataFrame axis=0 (column-wise) ────────────────────
print("\napply(axis=0) — column-wise max:")
print(df_fn[["Age","Score"]].apply("max"))

apply(axis=0) — column-wise max:
Age      35.0
Score    95.5
dtype: float64

In [67]:
# ── apply() on DataFrame axis=1 (row-wise) ────────────────────────
df_fn["AgeScoreSum"] = df_fn[["Age","Score"]].apply(lambda row: row["Age"] + row["Score"], axis=1)
print("\napply(axis=1) — Age + Score:\n", df_fn[["Name","Age","Score","AgeScoreSum"]])

apply(axis=1) — Age + Score:
       Name  Age  Score  AgeScoreSum
0    Alice   25   88.5        113.5
1      Bob   30   92.0        122.0
2  Charlie   22   75.0         97.0
3    Diana   28   95.5        123.5
4      Eve   35   80.0        115.0
5    Frank   27   70.0         97.0

In [68]:
# ── applymap() / map() element-wise on whole DataFrame ───────────
df_num = pd.DataFrame({"A": [1.1, 2.5, 3.9], "B": [4.4, 5.7, 6.2]})

# pandas >= 2.1: use df.map(); older: df.applymap()
try:
    result = df_num.map(lambda x: round(x))
except AttributeError:
    result = df_num.applymap(lambda x: round(x))
print("\napplymap/map — round all values:\n", result)

applymap/map — round all values:
    A  B
0  1  4
1  2  6
2  4  6

---
## 16. Iteration Over Rows and Columns

> **Instructor Note:** Explicit loops over DataFrame rows are **slow**. Always prefer vectorized pandas operations. Use `iterrows()` / `itertuples()` only when necessary (e.g., row-by-row conditional logic that can't be vectorized).

| Method | Returns | Speed |
|--------|---------|-------|
| `iterrows()` | `(index, Series)` pairs | Slow |
| `itertuples()` | Named tuples | Faster than iterrows |
| Column loop | Column Series | Medium |
| **Vectorized** | Whole Series/array | **Fastest** |

In [69]:
df_iter = pd.DataFrame({
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age"  : [25, 30, 22],
    "Score": [88.5, 92.0, 75.0]
})

df_iter

      Name  Age  Score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   22   75.0

In [70]:
# ── iterrows() ───────────────────────────────────────────────────

print("--- iterrows() — (index, Series) pairs ---")
for idx, row in df_iter.iterrows():
    print(f"  Row {idx}: {row['Name']}, Age={row['Age']}, Score={row['Score']}")

--- iterrows() — (index, Series) pairs ---
  Row 0: Alice, Age=25, Score=88.5
  Row 1: Bob, Age=30, Score=92.0
  Row 2: Charlie, Age=22, Score=75.0

In [71]:
# ── itertuples() ─────────────────────────────────────────────────

print("\n--- itertuples() — named tuples (faster) ---")
for row in df_iter.itertuples():
    print(f"  Index={row.Index}, Name={row.Name}, Score={row.Score}")

--- itertuples() — named tuples (faster) ---
  Index=0, Name=Alice, Score=88.5
  Index=1, Name=Bob, Score=92.0
  Index=2, Name=Charlie, Score=75.0

In [72]:
# ── Iterate over columns ─────────────────────────────────────────

print("\n--- Iterate over columns ---")
for col_name in df_iter.columns:
    print(f"  Column '{col_name}': {df_iter[col_name].tolist()}")

--- Iterate over columns ---
  Column 'Name': ['Alice', 'Bob', 'Charlie']
  Column 'Age': [25, 30, 22]
  Column 'Score': [88.5, 92.0, 75.0]

In [73]:

# ── Preferred: vectorized alternative ────────────────────────────
print("\n--- Vectorized (preferred) — add bonus without loop ---")
df_iter["Bonus"]      = df_iter["Score"] * 0.1
df_iter["FinalScore"] = df_iter["Score"] + df_iter["Bonus"]
print(df_iter)

--- Vectorized (preferred) — add bonus without loop ---
      Name  Age  Score  Bonus  FinalScore
0    Alice   25   88.5   8.85       97.35
1      Bob   30   92.0   9.20      101.20
2  Charlie   22   75.0   7.50       82.50

---
## 17. Reset Index

### Characteristics
| Feature | Description |
|---------|-------------|
| **Index to column** | Old index becomes a regular column |
| **drop option** | `drop=True` discards the old index |
| **in-place operation** | `inplace=True` modifies without reassignment |

In [74]:
df_ri = pd.DataFrame({
    "Name" : ["Alice", "Bob", "Charlie", "Diana"],
    "Score": [88.5, 92.0, 75.0, 95.5]
}, index=["r0", "r1", "r2", "r3"])

print("Custom-indexed DataFrame:\n", df_ri)

Custom-indexed DataFrame:
        Name  Score
r0    Alice   88.5
r1      Bob   92.0
r2  Charlie   75.0
r3    Diana   95.5

In [75]:
# ── Default reset_index — index becomes column ────────────────────

print("\nreset_index() — old index becomes a column:")
print(df_ri.reset_index())

reset_index() — old index becomes a column:
  index     Name  Score
0    r0    Alice   88.5
1    r1      Bob   92.0
2    r2  Charlie   75.0
3    r3    Diana   95.5

In [76]:
# ── drop=True — discard old index ────────────────────────────────

print("\nreset_index(drop=True) — old index is discarded:")
print(df_ri.reset_index(drop=True))

reset_index(drop=True) — old index is discarded:
      Name  Score
0    Alice   88.5
1      Bob   92.0
2  Charlie   75.0
3    Diana   95.5

In [77]:
# ── inplace=True ──────────────────────────────────────────────────
df_ri_copy = df_ri.copy()
df_ri_copy.reset_index(inplace=True)
print("\nreset_index(inplace=True):")
print(df_ri_copy)

# ── inplace + drop ────────────────────────────────────────────────
df_ri_copy2 = df_ri.copy()
df_ri_copy2.reset_index(drop=True, inplace=True)
print("\nreset_index(drop=True, inplace=True):")
print(df_ri_copy2)

reset_index(inplace=True):
  index     Name  Score
0    r0    Alice   88.5
1    r1      Bob   92.0
2    r2  Charlie   75.0
3    r3    Diana   95.5

reset_index(drop=True, inplace=True):
      Name  Score
0    Alice   88.5
1      Bob   92.0
2  Charlie   75.0
3    Diana   95.5

In [78]:
# ── Resetting a MultiIndex ────────────────────────────────────────
df_multi = pd.DataFrame({
    "Score": [88.5, 92.0, 75.0, 95.5]
}, index=pd.MultiIndex.from_tuples(
    [("DS","Alice"),("ML","Bob"),("DS","Charlie"),("AI","Diana")],
    names=["Dept","Name"]
))
print("\nMultiIndex DataFrame:\n", df_multi)

print("\nreset_index() on MultiIndex:")
print(df_multi.reset_index())

MultiIndex DataFrame:
               Score
Dept Name
DS   Alice     88.5
ML   Bob       92.0
DS   Charlie   75.0
AI   Diana     95.5

reset_index() on MultiIndex:
  Dept     Name  Score
0   DS    Alice   88.5
1   ML      Bob   92.0
2   DS  Charlie   75.0
3   AI    Diana   95.5

---
## 18. Concatenation of DataFrames

### Types of Concatenation
| Type | axis | Description |
|------|------|-------------|
| **Vertical** | `axis=0` | Stack rows (default) |
| **Horizontal** | `axis=1` | Stack columns side by side |

In [79]:
df_a = pd.DataFrame({"Name": ["Alice", "Bob"],   "Score": [88, 92], "City": ["NY","LA"]})
df_b = pd.DataFrame({"Name": ["Charlie","Diana"], "Score": [75, 95], "City": ["NY","Chicago"]})
df_c = pd.DataFrame({"Name": ["Eve","Frank"],     "Age":   [35, 27], "Dept": ["ML","DS"]})

# ── Vertical concatenation (axis=0) ──────────────────────────────
print("--- Vertical concat (axis=0) ---")
df_vert = pd.concat([df_a, df_b], ignore_index=True)
print(df_vert)

--- Vertical concat (axis=0) ---
      Name  Score     City
0    Alice     88       NY
1      Bob     92       LA
2  Charlie     75       NY
3    Diana     95  Chicago

In [80]:
# ── Horizontal concatenation (axis=1) ────────────────────────────
print("\n--- Horizontal concat (axis=1) ---")
df_horiz = pd.concat([df_a, df_c], axis=1)
print(df_horiz)

--- Horizontal concat (axis=1) ---
    Name  Score City   Name  Age Dept
0  Alice     88   NY    Eve   35   ML
1    Bob     92   LA  Frank   27   DS

In [81]:
# ── Concat with different columns (NaN for missing) ───────────────
print("\n--- Concat with different columns (df_a + df_c vertically) ---")
print(pd.concat([df_a, df_c], ignore_index=True))

--- Concat with different columns (df_a + df_c vertically) ---
    Name  Score City   Age Dept
0  Alice   88.0   NY   NaN  NaN
1    Bob   92.0   LA   NaN  NaN
2    Eve    NaN  NaN  35.0   ML
3  Frank    NaN  NaN  27.0   DS

In [82]:
# ── Concat with mismatched indices ────────────────────────────────

df_d = pd.DataFrame({"Score":[70,60]}, index=[10,11])
print("\n--- Concat with mismatched indices ---")
print(pd.concat([df_a[["Score"]], df_d]))

--- Concat with mismatched indices ---
    Score
0      88
1      92
10     70
11     60

In [83]:
# ── Hierarchical keys ─────────────────────────────────────────────
print("\n--- Concat with keys (creates MultiIndex) ---")
df_keyed = pd.concat([df_a, df_b], keys=["Batch1","Batch2"])
print(df_keyed)
print("\nAccess Batch2:", df_keyed.loc["Batch2"])

--- Concat with keys (creates MultiIndex) ---
             Name  Score     City
Batch1 0    Alice     88       NY
       1      Bob     92       LA
Batch2 0  Charlie     75       NY
       1    Diana     95  Chicago

Access Batch2:       Name  Score     City
0  Charlie     75       NY
1    Diana     95  Chicago

---
## 19. Merging DataFrames — `pd.merge()`

### Types of Join
| Join | Description |
|------|-------------|
| **inner** | Only matching keys in both tables |
| **left**  | All rows from left, matching from right |
| **right** | All rows from right, matching from left |
| **outer** | All rows from both, NaN where no match |

In [84]:
employees = pd.DataFrame({
    "EmpID" : [1, 2, 3, 4, 5],
    "Name"  : ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "DeptID": [10, 20, 10, 30, 20]
})

departments = pd.DataFrame({
    "DeptID"  : [10, 20, 40],
    "DeptName": ["Data Science", "Machine Learning", "DevOps"]
})

print("Employees:\n", employees)
print("\nDepartments:\n", departments)

Employees:
    EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      10
3      4    Diana      30
4      5      Eve      20

Departments:
    DeptID          DeptName
0      10      Data Science
1      20  Machine Learning
2      40            DevOps

In [85]:
# ── inner merge ───────────────────────────────────────────────────
print("\n--- INNER merge (only matching DeptIDs) ---")
print(pd.merge(employees, departments, on="DeptID", how="inner"))

--- INNER merge (only matching DeptIDs) ---
   EmpID     Name  DeptID          DeptName
0      1    Alice      10      Data Science
1      2      Bob      20  Machine Learning
2      3  Charlie      10      Data Science
3      5      Eve      20  Machine Learning

In [86]:
# ── left merge ────────────────────────────────────────────────────
print("\n--- LEFT merge (all employees kept) ---")
print(pd.merge(employees, departments, on="DeptID", how="left"))

--- LEFT merge (all employees kept) ---
   EmpID     Name  DeptID          DeptName
0      1    Alice      10      Data Science
1      2      Bob      20  Machine Learning
2      3  Charlie      10      Data Science
3      4    Diana      30               NaN
4      5      Eve      20  Machine Learning

In [87]:
# ── right merge ───────────────────────────────────────────────────
print("\n--- RIGHT merge (all departments kept) ---")
print(pd.merge(employees, departments, on="DeptID", how="right"))

--- RIGHT merge (all departments kept) ---
   EmpID     Name  DeptID          DeptName
0    1.0    Alice      10      Data Science
1    3.0  Charlie      10      Data Science
2    2.0      Bob      20  Machine Learning
3    5.0      Eve      20  Machine Learning
4    NaN      NaN      40            DevOps

In [88]:
# ── outer merge ───────────────────────────────────────────────────
print("\n--- OUTER merge (everything from both) ---")
print(pd.merge(employees, departments, on="DeptID", how="outer"))

--- OUTER merge (everything from both) ---
   EmpID     Name  DeptID          DeptName
0    1.0    Alice      10      Data Science
1    3.0  Charlie      10      Data Science
2    2.0      Bob      20  Machine Learning
3    5.0      Eve      20  Machine Learning
4    4.0    Diana      30               NaN
5    NaN      NaN      40            DevOps

In [89]:
# ── Merge on multiple keys ────────────────────────────────────────

df_sales  = pd.DataFrame({"Year":[2022,2022,2023], "Month":[1,2,1], "Sales":[100,150,200]})
df_target = pd.DataFrame({"Year":[2022,2022,2023], "Month":[1,2,1], "Target":[120,140,180]})

print("\n--- Merge on multiple keys (Year+Month) ---")
print(pd.merge(df_sales, df_target, on=["Year","Month"]))

--- Merge on multiple keys (Year+Month) ---
   Year  Month  Sales  Target
0  2022      1    100     120
1  2022      2    150     140
2  2023      1    200     180

In [90]:
# ── left_on / right_on / suffixes ────────────────────────────────

df_emp2  = pd.DataFrame({"ID":[1,2,3],"EmpName":["Alice","Bob","Charlie"],"Score":[88,92,75]})
df_dept2 = pd.DataFrame({"DID":[1,2,4],"DeptName":["DS","ML","AI"],"Score":[100,90,80]})

print("\n--- left_on / right_on / suffixes ---")
print(pd.merge(df_emp2, df_dept2, left_on="ID", right_on="DID", suffixes=("_emp","_dept")))

--- left_on / right_on / suffixes ---
   ID EmpName  Score_emp  DID DeptName  Score_dept
0   1   Alice         88    1       DS         100
1   2     Bob         92    2       ML          90

---
## 20. Joining DataFrames — `df.join()`

> **Key Difference:**
> - `merge()` joins on **column values**
> - `join()` joins on **index values** (by default)

### Types of Join: left (default), right, inner, outer

In [91]:
df_left = pd.DataFrame({
    "Name" : ["Alice","Bob","Charlie"],
    "Score": [88, 92, 75]
}, index=[1, 2, 3])

df_right = pd.DataFrame({
    "City": ["NY","LA","Chicago"],
    "Dept": ["DS","ML","AI"]
}, index=[2, 3, 4])   # index 1 is missing, index 4 is extra

print("Left DataFrame (index 1,2,3):\n", df_left)
print("\nRight DataFrame (index 2,3,4):\n", df_right)

Left DataFrame (index 1,2,3):
       Name  Score
1    Alice     88
2      Bob     92
3  Charlie     75

Right DataFrame (index 2,3,4):
       City Dept
2       NY   DS
3       LA   ML
4  Chicago   AI

In [92]:
# ── left join (default) ───────────────────────────────────────────

print("\n--- left join (keep all left rows) ---")
print(df_left.join(df_right, how="left"))

--- left join (keep all left rows) ---
      Name  Score City Dept
1    Alice     88  NaN  NaN
2      Bob     92   NY   DS
3  Charlie     75   LA   ML

In [93]:
# ── right join ────────────────────────────────────────────────────

print("\n--- right join (keep all right rows) ---")
print(df_left.join(df_right, how="right"))

--- right join (keep all right rows) ---
      Name  Score     City Dept
2      Bob   92.0       NY   DS
3  Charlie   75.0       LA   ML
4      NaN    NaN  Chicago   AI

In [94]:
# ── inner join ────────────────────────────────────────────────────

print("\n--- inner join (only matching indices) ---")
print(df_left.join(df_right, how="inner"))

--- inner join (only matching indices) ---
      Name  Score City Dept
2      Bob     92   NY   DS
3  Charlie     75   LA   ML

In [95]:
# ── outer join ────────────────────────────────────────────────────

print("\n--- outer join (all from both) ---")
print(df_left.join(df_right, how="outer"))

--- outer join (all from both) ---
      Name  Score     City Dept
1    Alice   88.0      NaN  NaN
2      Bob   92.0       NY   DS
3  Charlie   75.0       LA   ML
4      NaN    NaN  Chicago   AI

In [96]:
# ── merge vs join comparison ──────────────────────────────────────
print("\n=== Merge vs Join Comparison ===")
df_m_left  = pd.DataFrame({"EmpID":[1,2,3], "Name":["A","B","C"], "DeptID":[10,20,10]})
df_m_right = pd.DataFrame({"DeptID":[10,20], "DeptName":["DS","ML"]})

print("merge (on column DeptID):")
print(pd.merge(df_m_left, df_m_right, on="DeptID"))

df_j_left  = df_m_left.set_index("DeptID")
df_j_right = df_m_right.set_index("DeptID")
print("\njoin (on index DeptID):")
print(df_j_left.join(df_j_right, how="left"))

=== Merge vs Join Comparison ===
merge (on column DeptID):
   EmpID Name  DeptID DeptName
0      1    A      10       DS
1      2    B      20       ML
2      3    C      10       DS

join (on index DeptID):
        EmpID Name DeptName
DeptID
10          1    A       DS
20          2    B       ML
10          3    C       DS

---
## 21. GroupBy Operations

### The Split → Apply → Combine Pattern

```
Original DataFrame
       ↓
   SPLIT (group by key)
   ┌──────┬──────┐
   │ DS   │ ML   │  ← groups
   └──────┴──────┘
       ↓
   APPLY (aggregation / transform / filter)
       ↓
   COMBINE (assemble result)
```

| Step | Description |
|------|-------------|
| **Split** | Divide DataFrame into groups by one or more keys |
| **Apply** | Apply a function to each group independently |
| **Combine** | Merge the results into a single DataFrame/Series |

In [97]:
df_gb = pd.DataFrame({
    "Name"  : ["Alice","Bob","Charlie","Diana","Eve","Frank","Grace","Henry"],
    "Dept"  : ["DS","ML","DS","AI","ML","DS","AI","ML"],
    "City"  : ["NY","LA","NY","Chicago","NY","LA","Chicago","NY"],
    "Score" : [88, 92, 75, 95, 80, 70, 85, 90],
    "Salary": [70000, 80000, 65000, 90000, 75000, 60000, 85000, 78000],
    "Exp"   : [3, 5, 2, 7, 4, 1, 6, 4]
})

print("Base DataFrame:\n", df_gb)

Base DataFrame:
       Name Dept     City  Score  Salary  Exp
0    Alice   DS       NY     88   70000    3
1      Bob   ML       LA     92   80000    5
2  Charlie   DS       NY     75   65000    2
3    Diana   AI  Chicago     95   90000    7
4      Eve   ML       NY     80   75000    4
5    Frank   DS       LA     70   60000    1
6    Grace   AI  Chicago     85   85000    6
7    Henry   ML       NY     90   78000    4

In [98]:
# ── Basic GroupBy ─────────────────────────────────────────────────

print("\n--- GroupBy single column (Dept) — mean Score ---")
print(df_gb.groupby("Dept")["Score"].mean())

--- GroupBy single column (Dept) — mean Score ---
Dept
AI    90.000000
DS    77.666667
ML    87.333333
Name: Score, dtype: float64

In [99]:
# ── GroupBy on multiple columns ────────────────────────────────────

print("\n--- GroupBy multiple columns (Dept + City) — mean Score ---")
print(df_gb.groupby(["Dept","City"])["Score"].mean())

--- GroupBy multiple columns (Dept + City) — mean Score ---
Dept  City
AI    Chicago    90.0
DS    LA         70.0
      NY         81.5
ML    LA         92.0
      NY         85.0
Name: Score, dtype: float64

In [100]:
# ── Multiple aggregation functions ────────────────────────────────

print("\n--- agg() — multiple functions on Score ---")
print(df_gb.groupby("Dept")["Score"].agg(["mean","min","max","std","count"]))

print("\n--- agg() — different functions per column ---")
print(df_gb.groupby("Dept").agg({
    "Score" : ["mean","max"],
    "Salary": ["mean","sum"],
    "Exp"   : "mean"
}))

--- agg() — multiple functions on Score ---
           mean  min  max       std  count
Dept
AI    90.000000   85   95  7.071068      2
DS    77.666667   70   88  9.291573      3
ML    87.333333   80   92  6.429101      3

--- agg() — different functions per column ---
          Score            Salary               Exp
           mean max          mean     sum      mean
Dept
AI    90.000000  95  87500.000000  175000  6.500000
DS    77.666667  88  65000.000000  195000  2.000000
ML    87.333333  92  77666.666667  233000  4.333333

In [101]:
# ── filter() — keep groups satisfying a condition ─────────────────
print("--- filter() — keep Depts where mean Score > 82 ---")

filtered = df_gb.groupby("Dept").filter(lambda g: g["Score"].mean() > 82)
print(filtered)

--- filter() — keep Depts where mean Score > 82 ---
    Name Dept     City  Score  Salary  Exp
1    Bob   ML       LA     92   80000    5
3  Diana   AI  Chicago     95   90000    7
4    Eve   ML       NY     80   75000    4
6  Grace   AI  Chicago     85   85000    6
7  Henry   ML       NY     90   78000    4

In [102]:
# ── transform() — group-wise transformation (preserves shape) ─────

print("\n--- transform() — normalize Score within each Dept (z-score) ---")
df_gb["Score_zscore"] = df_gb.groupby("Dept")["Score"].transform(
    lambda x: (x - x.mean()) / x.std()
)
print(df_gb[["Name","Dept","Score","Score_zscore"]].round(3))

print("\n--- transform('mean') — fill each row with its group mean ---")
df_gb["Dept_AvgScore"] = df_gb.groupby("Dept")["Score"].transform("mean")
print(df_gb[["Name","Dept","Score","Dept_AvgScore"]])

--- transform() — normalize Score within each Dept (z-score) ---
      Name Dept  Score  Score_zscore
0    Alice   DS     88         1.112
1      Bob   ML     92         0.726
2  Charlie   DS     75        -0.287
3    Diana   AI     95         0.707
4      Eve   ML     80        -1.141
5    Frank   DS     70        -0.825
6    Grace   AI     85        -0.707
7    Henry   ML     90         0.415

--- transform('mean') — fill each row with its group mean ---
      Name Dept  Score  Dept_AvgScore
0    Alice   DS     88      77.666667
1      Bob   ML     92      87.333333
2  Charlie   DS     75      77.666667
3    Diana   AI     95      90.000000
4      Eve   ML     80      87.333333
5    Frank   DS     70      77.666667
6    Grace   AI     85      90.000000
7    Henry   ML     90      87.333333

In [103]:
# ── GroupBy with custom function ──────────────────────────────────
print("\n--- Custom agg function — Score range (max-min) per Dept ---")
def score_range(series):
    return series.max() - series.min()

print(df_gb.groupby("Dept")["Score"].agg(score_range))

--- Custom agg function — Score range (max-min) per Dept ---
Dept
AI    10
DS    18
ML    12
Name: Score, dtype: int64

In [104]:
# ── Named aggregation (pandas >= 0.25) ────────────────────────────
print("\n--- Named aggregation ---")
result = df_gb.groupby("Dept").agg(
    avg_score   = ("Score",  "mean"),
    total_salary= ("Salary", "sum"),
    headcount   = ("Name",   "count")
)
print(result)

--- Named aggregation ---
      avg_score  total_salary  headcount
Dept
AI    90.000000        175000          2
DS    77.666667        195000          3
ML    87.333333        233000          3

---
## 22. Pivot Tables — `pd.pivot_table()`

### What is a Pivot Table?
A **Pivot Table** reshapes data by aggregating values across two axes.  
Think of it as a powerful GroupBy with a 2D grid output.

```
pd.pivot_table(df,
    values  = 'column_to_aggregate',
    index   = 'rows',
    columns = 'columns',
    aggfunc = 'mean'   # default
)
```

In [105]:
df_pv = pd.DataFrame({
    "Name"  : ["Alice","Bob","Charlie","Diana","Eve","Frank","Grace","Henry","Iris","Jack"],
    "Dept"  : ["DS","ML","DS","AI","ML","DS","AI","ML","DS","AI"],
    "City"  : ["NY","LA","NY","Chicago","NY","LA","Chicago","NY","LA","NY"],
    "Score" : [88, 92, 75, 95, 80, 70, 85, 90, 78, 88],
    "Salary": [70000, 80000, 65000, 90000, 75000, 60000, 85000, 78000, 72000, 82000],
    "Quarter": ["Q1","Q2","Q1","Q2","Q1","Q2","Q1","Q2","Q1","Q2"]
})

df_pv

      Name Dept     City  Score  Salary Quarter
0    Alice   DS       NY     88   70000      Q1
1      Bob   ML       LA     92   80000      Q2
2  Charlie   DS       NY     75   65000      Q1
3    Diana   AI  Chicago     95   90000      Q2
4      Eve   ML       NY     80   75000      Q1
5    Frank   DS       LA     70   60000      Q2
6    Grace   AI  Chicago     85   85000      Q1
7    Henry   ML       NY     90   78000      Q2
8     Iris   DS       LA     78   72000      Q1
9     Jack   AI       NY     88   82000      Q2

In [106]:
# ── Basic pivot table ─────────────────────────────────────────────
print("--- Basic pivot table: mean Score by Dept × City ---")
pt1 = pd.pivot_table(df_pv, values="Score", index="Dept", columns="City", aggfunc="mean")
print(pt1)

--- Basic pivot table: mean Score by Dept × City ---
City  Chicago    LA    NY
Dept
AI       90.0   NaN  88.0
DS        NaN  74.0  81.5
ML        NaN  92.0  85.0

In [107]:
# ── Multiple aggregation functions ────────────────────────────────
print("\n--- Multiple aggfunc: mean and max Score ---")
pt2 = pd.pivot_table(df_pv, values="Score", index="Dept", columns="City",
                     aggfunc=["mean","max"])
print(pt2)

--- Multiple aggfunc: mean and max Score ---
        mean                 max
City Chicago    LA    NY Chicago    LA    NY
Dept
AI      90.0   NaN  88.0    95.0   NaN  88.0
DS       NaN  74.0  81.5     NaN  78.0  88.0
ML       NaN  92.0  85.0     NaN  92.0  90.0

In [108]:
# ── Handling missing values with fill_value ────────────────────────
print("\n--- Handle NaN with fill_value=0 ---")
pt3 = pd.pivot_table(df_pv, values="Score", index="Dept", columns="City",
                     aggfunc="mean", fill_value=0)
print(pt3)

--- Handle NaN with fill_value=0 ---
City  Chicago    LA    NY
Dept
AI       90.0   0.0  88.0
DS        0.0  74.0  81.5
ML        0.0  92.0  85.0

In [109]:
# ── Adding margins (row/column subtotals) ─────────────────────────
print("\n--- margins=True adds row/column totals ---")
pt4 = pd.pivot_table(df_pv, values="Score", index="Dept", columns="City",
                     aggfunc="mean", fill_value=0, margins=True, margins_name="TOTAL")
print(pt4)

--- margins=True adds row/column totals ---
City   Chicago    LA    NY      TOTAL
Dept
AI        90.0   0.0  88.0  89.333333
DS         0.0  74.0  81.5  77.750000
ML         0.0  92.0  85.0  87.333333
TOTAL     90.0  80.0  84.2  84.100000

In [110]:
# ── Multi-level pivot table ───────────────────────────────────────
print("\n--- Multi-level pivot: index=[Dept,Quarter], columns=City ---")
pt5 = pd.pivot_table(df_pv, values="Score", index=["Dept","Quarter"],
                     columns="City", aggfunc="mean", fill_value=0)
print(pt5)

--- Multi-level pivot: index=[Dept,Quarter], columns=City ---
City          Chicago    LA    NY
Dept Quarter
AI   Q1          85.0   0.0   0.0
     Q2          95.0   0.0  88.0
DS   Q1           0.0  78.0  81.5
     Q2           0.0  70.0   0.0
ML   Q1           0.0   0.0  80.0
     Q2           0.0  92.0  90.0

---
## 23. Working with DateTime

### DateTime Data Types in Pandas

| Type | Description | Example |
|------|-------------|---------|
| `datetime64[ns]` | Absolute timestamp | `2024-01-15 08:30:00` |
| `timedelta64[ns]` | Duration / difference between times | `3 days 04:00:00` |

### The `.dt` Accessor
Just like `.str` for strings, `.dt` gives access to datetime properties on a Series.

In [111]:
# ── Converting strings to datetime ───────────────────────────────
dates_str = pd.Series(["2024-01-15", "2024-03-22", "2024-07-04",
                        "2024-11-28", "2025-02-14"])
dates = pd.to_datetime(dates_str)
print("Converted to datetime:\n", dates)
print("dtype:", dates.dtype)

Converted to datetime:
 0   2024-01-15
1   2024-03-22
2   2024-07-04
3   2024-11-28
4   2025-02-14
dtype: datetime64[ns]
dtype: datetime64[ns]

In [112]:
# ── Custom format string ──────────────────────────────────────────
custom_dates = pd.to_datetime(["15/01/2024", "22/03/2024"], format="%d/%m/%Y")
print("\nCustom format parsing:", custom_dates)

Custom format parsing: DatetimeIndex(['2024-01-15', '2024-03-22'], dtype='datetime64[ns]', freq=None)

In [113]:
# ── Extracting date components with .dt accessor ──────────────────
df_dt = pd.DataFrame({
    "Name"      : ["Alice","Bob","Charlie","Diana","Eve"],
    "JoinDate"  : pd.to_datetime(["2022-03-15","2020-07-01","2023-01-20","2019-11-30","2024-06-05"]),
    "BirthDate" : pd.to_datetime(["1995-08-22","1988-04-10","1997-12-05","1992-06-15","2000-09-30"])
})

print("\nDate components extracted with .dt:\n")
df_dt["Year"]    = df_dt["JoinDate"].dt.year
df_dt["Month"]   = df_dt["JoinDate"].dt.month
df_dt["Day"]     = df_dt["JoinDate"].dt.day
df_dt["Weekday"] = df_dt["JoinDate"].dt.weekday   # 0=Monday
df_dt["DayName"] = df_dt["JoinDate"].dt.day_name()
df_dt["Quarter"] = df_dt["JoinDate"].dt.quarter
print(df_dt[["Name","JoinDate","Year","Month","Day","Weekday","DayName","Quarter"]])

Date components extracted with .dt:

      Name   JoinDate  Year  Month  Day  Weekday    DayName  Quarter
0    Alice 2022-03-15  2022      3   15        1    Tuesday        1
1      Bob 2020-07-01  2020      7    1        2  Wednesday        3
2  Charlie 2023-01-20  2023      1   20        4     Friday        1
3    Diana 2019-11-30  2019     11   30        5   Saturday        4
4      Eve 2024-06-05  2024      6    5        2  Wednesday        2

In [114]:
# ── Creating date ranges ─────────────────────────────────────────
print("--- pd.date_range: daily frequency ---")
dr_daily = pd.date_range(start="2024-01-01", end="2024-01-10", freq="D")
print(dr_daily)

print("\n--- pd.date_range: monthly frequency (6 periods) ---")
dr_monthly = pd.date_range(start="2024-01-01", periods=6, freq="ME")
print(dr_monthly)

print("\n--- pd.date_range: business days ---")
dr_biz = pd.date_range(start="2024-01-01", periods=5, freq="B")
print(dr_biz)

print("\n--- pd.date_range: hourly ---")
dr_hourly = pd.date_range(start="2024-01-01 08:00", periods=5, freq="h")
print(dr_hourly)

--- pd.date_range: daily frequency ---
DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06',
               '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

--- pd.date_range: monthly frequency (6 periods) ---
DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30', '2024-05-31', '2024-06-30'], dtype='datetime64[ns]', freq='ME')

--- pd.date_range: business days ---
DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05'], dtype='datetime64[ns]', freq='B')

--- pd.date_range: hourly ---
DatetimeIndex(['2024-01-01 08:00:00', '2024-01-01 09:00:00', '2024-01-01 10:00:00',
               '2024-01-01 11:00:00', '2024-01-01 12:00:00'],
              dtype='datetime64[ns]', freq='h')

In [115]:
# ── Timedelta operations ──────────────────────────────────────────
print("\n--- Timedelta: calculate tenure in days ---")
df_dt["Today"]  = pd.Timestamp("2024-12-31")
df_dt["Tenure"] = df_dt["Today"] - df_dt["JoinDate"]
print(df_dt[["Name","JoinDate","Tenure"]])

print("\n--- Extract days from timedelta using .dt.days ---")
df_dt["TenureDays"]  = df_dt["Tenure"].dt.days
df_dt["TenureYears"] = (df_dt["TenureDays"] / 365).round(1)
print(df_dt[["Name","TenureDays","TenureYears"]])

print("\n--- Adding timedelta offsets ---")
df_dt["ContractEnd"] = df_dt["JoinDate"] + pd.Timedelta(days=365)
print(df_dt[["Name","JoinDate","ContractEnd"]])

--- Timedelta: calculate tenure in days ---
      Name   JoinDate    Tenure
0    Alice 2022-03-15 1022 days
1      Bob 2020-07-01 1644 days
2  Charlie 2023-01-20  711 days
3    Diana 2019-11-30 1858 days
4      Eve 2024-06-05  209 days

--- Extract days from timedelta using .dt.days ---
      Name  TenureDays  TenureYears
0    Alice        1022          2.8
1      Bob        1644          4.5
2  Charlie         711          1.9
3    Diana        1858          5.1
4      Eve         209          0.6

--- Adding timedelta offsets ---
      Name   JoinDate ContractEnd
0    Alice 2022-03-15  2023-03-15
1      Bob 2020-07-01  2021-07-01
2  Charlie 2023-01-20  2024-01-20
3    Diana 2019-11-30  2020-11-29
4      Eve 2024-06-05  2025-06-05

In [116]:
# ── Timezones ────────────────────────────────────────────────────
print("\n--- Timezone localization and conversion ---")
ts = pd.Timestamp("2024-06-15 09:00")
ts_utc = ts.tz_localize("UTC")
ts_ist = ts_utc.tz_convert("Asia/Kolkata")
ts_est = ts_utc.tz_convert("US/Eastern")
print(f"UTC : {ts_utc}")
print(f"IST : {ts_ist}")
print(f"EST : {ts_est}")

--- Timezone localization and conversion ---
UTC : 2024-06-15 09:00:00+00:00
IST : 2024-06-15 14:30:00+05:30
EST : 2024-06-15 05:00:00-04:00

---
## 24. Reading and Writing Files — CSV, Excel, JSON

### Common Parameters for `read_csv()`
| Parameter | Description |
|-----------|-------------|
| `filepath` | File path or URL |
| `sep` | Delimiter (default `,`) |
| `header` | Row number for column names |
| `index_col` | Column to use as row index |
| `usecols` | Select specific columns to load |
| `na_values` | Values to treat as NaN |
| `nrows` | Number of rows to read |
| `dtype` | Force column data types |

In [117]:
import os, io

df_io = pd.DataFrame({
    "Name"   : ["Alice","Bob","Charlie","Diana","Eve"],
    "Dept"   : ["DS","ML","DS","AI","ML"],
    "Score"  : [88.5, 92.0, 75.0, 95.5, 80.0],
    "Salary" : [70000, 80000, 65000, 90000, 75000],
    "JoinDate": pd.to_datetime(["2022-03-15","2020-07-01","2023-01-20","2019-11-30","2024-06-05"])
})

df_io

      Name Dept  Score  Salary   JoinDate
0    Alice   DS   88.5   70000 2022-03-15
1      Bob   ML   92.0   80000 2020-07-01
2  Charlie   DS   75.0   65000 2023-01-20
3    Diana   AI   95.5   90000 2019-11-30
4      Eve   ML   80.0   75000 2024-06-05

In [118]:
import os

folder = r"c:\learning\AIML_learning\pandas"
os.makedirs(folder, exist_ok=True)

csv_path = os.path.join(folder, "sample_data.csv")

df_io.to_csv(csv_path, index=False)
print("CSV saved successfully!")

CSV saved successfully!

In [119]:
import os
print(os.getcwd())

d:\0--ALL_GitHub_Projects\1_My_ALL_Assignments_and_Notes\4--Pandas Assignments\Assignments Pandas\Final Submission

In [120]:
csv_path = "sample_data.csv"

df_io.to_csv(csv_path, index=False)

df_read_csv = pd.read_csv(csv_path)
df_read_csv

      Name Dept  Score  Salary    JoinDate
0    Alice   DS   88.5   70000  2022-03-15
1      Bob   ML   92.0   80000  2020-07-01
2  Charlie   DS   75.0   65000  2023-01-20
3    Diana   AI   95.5   90000  2019-11-30
4      Eve   ML   80.0   75000  2024-06-05

In [121]:
# ────────────────────────────────────────────────────────────────
# CSV
# ────────────────────────────────────────────────────────────────
csv_path = os.path.join(folder, "sample_data.csv")

# Write CSV
df_io.to_csv(csv_path, index=False)
print("CSV written to:", csv_path)

# Read CSV
df_read_csv = pd.read_csv(csv_path)
print("\nRead CSV (all columns):\n", df_read_csv)

# Read with specific columns
df_subset = pd.read_csv(csv_path, usecols=["Name","Dept","Score"])
print("\nRead CSV (usecols=['Name','Dept','Score']):\n", df_subset)

# Read with custom na_values and nrows
df_nrows = pd.read_csv(csv_path, nrows=3)
print("\nRead CSV (nrows=3):\n", df_nrows)

# Write CSV with custom separator
tsv_path = csv_path.replace(".csv", ".tsv")
df_io.to_csv(tsv_path, index=False, sep="\t")
df_tsv = pd.read_csv(tsv_path, sep="\t")
print("\nTSV read back:\n", df_tsv.head(2))

CSV written to: c:\learning\AIML_learning\pandas\sample_data.csv

Read CSV (all columns):
       Name Dept  Score  Salary    JoinDate
0    Alice   DS   88.5   70000  2022-03-15
1      Bob   ML   92.0   80000  2020-07-01
2  Charlie   DS   75.0   65000  2023-01-20
3    Diana   AI   95.5   90000  2019-11-30
4      Eve   ML   80.0   75000  2024-06-05

Read CSV (usecols=['Name','Dept','Score']):
       Name Dept  Score
0    Alice   DS   88.5
1      Bob   ML   92.0
2  Charlie   DS   75.0
3    Diana   AI   95.5
4      Eve   ML   80.0

Read CSV (nrows=3):
       Name Dept  Score  Salary    JoinDate
0    Alice   DS   88.5   70000  2022-03-15
1      Bob   ML   92.0   80000  2020-07-01
2  Charlie   DS   75.0   65000  2023-01-20

TSV read back:
     Name Dept  Score  Salary    JoinDate
0  Alice   DS   88.5   70000  2022-03-15
1    Bob   ML   92.0   80000  2020-07-01

In [122]:
# ────────────────────────────────────────────────────────────────
# Excel
# ────────────────────────────────────────────────────────────────
excel_path = r"c:\learning\AIML_learning\pandas\sample_data.xlsx"

# Write Excel — multiple sheets
try:
    with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
        df_io.to_excel(writer, sheet_name="Employees", index=False)
        df_io[df_io["Dept"]=="DS"].to_excel(writer, sheet_name="DS_Team", index=False)
    print("Excel written with 2 sheets:", excel_path)

    # Read specific sheet
    df_excel = pd.read_excel(excel_path, sheet_name="Employees")
    print("\nRead Excel (sheet='Employees'):\n", df_excel)

    df_ds = pd.read_excel(excel_path, sheet_name="DS_Team")
    print("\nRead Excel (sheet='DS_Team'):\n", df_ds)

    # Read all sheets into a dict
    all_sheets = pd.read_excel(excel_path, sheet_name=None)
    print("\nSheets loaded:", list(all_sheets.keys()))
except ImportError:
    print("openpyxl not installed — run: pip install openpyxl")

Excel written with 2 sheets: c:\learning\AIML_learning\pandas\sample_data.xlsx

Read Excel (sheet='Employees'):
       Name Dept  Score  Salary   JoinDate
0    Alice   DS   88.5   70000 2022-03-15
1      Bob   ML   92.0   80000 2020-07-01
2  Charlie   DS   75.0   65000 2023-01-20
3    Diana   AI   95.5   90000 2019-11-30
4      Eve   ML   80.0   75000 2024-06-05

Read Excel (sheet='DS_Team'):
       Name Dept  Score  Salary   JoinDate
0    Alice   DS   88.5   70000 2022-03-15
1  Charlie   DS   75.0   65000 2023-01-20

Sheets loaded: ['Employees', 'DS_Team']

In [123]:
# ────────────────────────────────────────────────────────────────
# JSON
# ────────────────────────────────────────────────────────────────
json_path = r"c:\learning\AIML_learning\pandas\sample_data.json"

# Write JSON — orient options: 'records', 'index', 'columns', 'split', 'table'
df_io_json = df_io[["Name","Dept","Score","Salary"]]   # drop datetime for clean JSON

df_io_json.to_json(json_path, orient="records", indent=2)
print("JSON written (orient='records'):", json_path)

# Read JSON
df_json = pd.read_json(json_path, orient="records")
print("\nRead JSON:\n", df_json)

# Different orientations
print("\n--- orient='index' ---")
print(df_io_json.to_json(orient="index"))

print("\n--- orient='columns' ---")
print(df_io_json.to_json(orient="columns"))

print("\n--- orient='split' ---")
print(df_io_json.to_json(orient="split"))

JSON written (orient='records'): c:\learning\AIML_learning\pandas\sample_data.json

Read JSON:
       Name Dept  Score  Salary
0    Alice   DS   88.5   70000
1      Bob   ML   92.0   80000
2  Charlie   DS   75.0   65000
3    Diana   AI   95.5   90000
4      Eve   ML   80.0   75000

--- orient='index' ---
{"0":{"Name":"Alice","Dept":"DS","Score":88.5,"Salary":70000},"1":{"Name":"Bob","Dept":"ML","Score":92.0,"Salary":80000},"2":{"Name":"Charlie","Dept":"DS","Score":75.0,"Salary":65000},"3":{"Name":"Diana","Dept":"AI","Score":95.5,"Salary":90000},"4":{"Name":"Eve","Dept":"ML","Score":80.0,"Salary":75000}}

--- orient='columns' ---
{"Name":{"0":"Alice","1":"Bob","2":"Charlie","3":"Diana","4":"Eve"},"Dept":{"0":"DS","1":"ML","2":"DS","3":"AI","4":"ML"},"Score":{"0":88.5,"1":92.0,"2":75.0,"3":95.5,"4":80.0},"Salary":{"0":70000,"1":80000,"2":65000,"3":90000,"4":75000}}

--- orient='split' ---
{"columns":["Name","Dept","Score","Salary"],"index":[0,1,2,3,4],"data":[["Alice","DS",88.5,70000],["Bob","ML",92.0,80000],["Charlie","DS",75.0,65000],["Diana","AI",95.5,90000],["Eve","ML",80.0,75000]]}

---
## 25. Handling Large Datasets

### Why It Matters
In real-world ML projects, datasets can be **gigabytes** in size. Loading them naively into memory crashes your kernel.

### Strategies
| Strategy | Tool | Description |
|----------|------|-------------|
| **Chunking** | `chunksize` | Read file in pieces |
| **Optimize dtypes** | `astype()` | Downcast int/float, use category |
| **Monitor memory** | `memory_usage()` | Track DataFrame RAM usage |
| **Partial load** | `nrows` | Load only first N rows for exploration |

In [124]:
# ── Generate a large sample CSV for demonstration ─────────────────
large_csv = r"c:\learning\AIML_learning\pandas\large_sample.csv"

np.random.seed(42)
n = 100_000
depts  = np.random.choice(["DS","ML","AI","DevOps","Cloud"], n)
cities = np.random.choice(["NY","LA","Chicago","Houston","Phoenix"], n)

df_large_gen = pd.DataFrame({
    "EmpID"  : np.arange(1, n+1),
    "Name"   : [f"Emp_{i}" for i in range(n)],
    "Dept"   : depts,
    "City"   : cities,
    "Age"    : np.random.randint(22, 60, n),
    "Score"  : np.random.uniform(50, 100, n).round(2),
    "Salary" : np.random.randint(40000, 120000, n),
    "Exp"    : np.random.randint(0, 20, n)
})
df_large_gen.to_csv(large_csv, index=False)
print(f"Generated {n:,} row CSV at: {large_csv}")
print(f"   File size: {os.path.getsize(large_csv)/1024:.1f} KB")

Generated 100,000 row CSV at: c:\learning\AIML_learning\pandas\large_sample.csv
   File size: 4378.0 KB

In [125]:
# ── nrows: load first N rows for quick inspection ─────────────────
print("--- nrows=5: quick preview ---")
df_preview = pd.read_csv(large_csv, nrows=5)
print(df_preview)

# ── Chunking: process file in pieces ──────────────────────────────
print("\n--- Chunking: compute dept-wise mean salary without loading full file ---")
chunk_size = 10_000
dept_salary_totals = {}
dept_counts        = {}

for chunk in pd.read_csv(large_csv, chunksize=chunk_size):
    for dept, grp in chunk.groupby("Dept"):
        dept_salary_totals[dept] = dept_salary_totals.get(dept, 0) + grp["Salary"].sum()
        dept_counts[dept]        = dept_counts.get(dept, 0) + len(grp)

dept_avg = {d: dept_salary_totals[d] / dept_counts[d] for d in dept_salary_totals}
print("Dept-wise mean Salary (via chunking):")
for d, avg in sorted(dept_avg.items()):
    print(f"  {d}: ${avg:,.0f}")

--- nrows=5: quick preview ---
   EmpID   Name    Dept     City  Age  Score  Salary  Exp
0      1  Emp_0  DevOps       LA   32  56.94   68942   11
1      2  Emp_1   Cloud       NY   44  81.56   75275    1
2      3  Emp_2      AI  Chicago   45  72.45   89519    6
3      4  Emp_3   Cloud  Houston   38  80.43   60020    5
4      5  Emp_4   Cloud  Houston   50  51.34  112729    2

--- Chunking: compute dept-wise mean salary without loading full file ---
Dept-wise mean Salary (via chunking):
  AI: $79,895
  Cloud: $80,215
  DS: $80,299
  DevOps: $79,902
  ML: $79,812

In [126]:
# ── Memory monitoring ─────────────────────────────────────────────
df_mem = pd.read_csv(large_csv)
print("--- memory_usage(deep=True) BEFORE optimization ---")
mem_before = df_mem.memory_usage(deep=True)
print(mem_before)
total_before = mem_before.sum() / 1024**2
print(f"\nTotal memory BEFORE: {total_before:.2f} MB")

# ── Dtype optimization ────────────────────────────────────────────
print("\n--- Optimizing dtypes ---")
print("BEFORE dtypes:\n", df_mem.dtypes)

df_opt = df_mem.copy()

# object → category (low-cardinality columns)
for col in ["Dept", "City"]:
    df_opt[col] = df_opt[col].astype("category")

# int64 → int32 (safe if values fit in int32 range)
for col in ["EmpID", "Age", "Salary", "Exp"]:
    df_opt[col] = df_opt[col].astype("int32")

# float64 → float32
df_opt["Score"] = df_opt["Score"].astype("float32")

print("\nAFTER dtypes:\n", df_opt.dtypes)

mem_after = df_opt.memory_usage(deep=True)
total_after = mem_after.sum() / 1024**2
print(f"\nTotal memory BEFORE : {total_before:.2f} MB")
print(f"Total memory AFTER  : {total_after:.2f} MB")
print(f"Memory SAVED        : {total_before - total_after:.2f} MB ({(1 - total_after/total_before)*100:.1f}% reduction)")

--- memory_usage(deep=True) BEFORE optimization ---
Index         132
EmpID      800000
Name      6588890
Dept      6040485
City      6199645
Age        800000
Score      800000
Salary     800000
Exp        800000
dtype: int64

Total memory BEFORE: 21.77 MB

--- Optimizing dtypes ---
BEFORE dtypes:
 EmpID       int64
Name       object
Dept       object
City       object
Age         int64
Score     float64
Salary      int64
Exp         int64
dtype: object

AFTER dtypes:
 EmpID        int32
Name        object
Dept      category
City      category
Age          int32
Score      float32
Salary       int32
Exp          int32
dtype: object

Total memory BEFORE : 21.77 MB
Total memory AFTER  : 8.38 MB
Memory SAVED        : 13.39 MB (61.5% reduction)

---
## Mini Exercises

### Exercise Set 1 — Series & DataFrame Basics
```
1. Create a Series of 5 students' marks with custom index (student names).
2. Create a DataFrame from a list of dicts representing 4 employees 
   (Name, Age, Dept, Salary). Add a 'Bonus' column = 10% of Salary.
3. Rename columns: 'Dept' → 'Department', 'Salary' → 'CTC'.
```

### Exercise Set 2 — Indexing & Selection
```
4. Using .loc, select employees whose Salary > 60000 AND Dept == 'DS'.
5. Using .iloc, select rows 1-3 and columns 0-2.
6. Set 'Name' as index and access data for a specific employee.
```

### Exercise Set 3 — Data Cleaning
```
7. Given a DataFrame with missing values, fill numeric NaN with column mean,
   and string NaN with 'Unknown'.
8. Find and remove duplicate rows.
9. Convert an 'Age' column stored as strings to integers.
10. Use str.strip() and str.title() to clean a messy 'Name' column.
```

### Exercise Set 4 — Manipulation & GroupBy
```
11. Filter employees with Score > 80, sort by Score descending.
12. Use groupby to find:
    - Count per Department
    - Mean Salary per Department
    - Top scorer per Department
13. Create a pivot table showing mean Salary by Dept × City.
```

### Exercise Set 5 — DateTime & I/O
```
14. Parse a list of date strings, extract year/month/weekday.
15. Calculate the number of days between two date columns.
16. Read a CSV, optimize dtypes, compare memory before/after.
```

---
## Mini Exercises

### Exercise Set 1 — Series & DataFrame Basics
```
1. Create a Series of 5 students' marks with custom index (student names).
2. Create a DataFrame from a list of dicts representing 4 employees 
   (Name, Age, Dept, Salary). Add a 'Bonus' column = 10% of Salary.
3. Rename columns: 'Dept' → 'Department', 'Salary' → 'CTC'.
```

#### 1. Create a Series of 5 students' marks with custom index (student names).

In [127]:
# series = index + values
import pandas as pd

marks = pd.Series(
    [85, 92, 78, 88, 95],
    index=["Rahul", "Ganraj", "Priya", "Neha", "Ravi"]
)

print(marks)

Rahul     85
Ganraj    92
Priya     78
Neha      88
Ravi      95
dtype: int64

#### 2. Create a DataFrame from a list of dicts representing 4 employees (Name, Age, Dept, Salary). Add a 'Bonus' column = 10% of Salary.

In [128]:
employees = [
    {"Name": "Rahul", "Age": 25, "Dept": "DS", "Salary": 70000},
    {"Name": "Ganraj", "Age": 28, "Dept": "DE", "Salary": 80000},
    {"Name": "Priya", "Age": 26, "Dept": "DS", "Salary": 65000},
    {"Name": "Neha", "Age": 30, "Dept": "ML", "Salary": 90000}
]

df = pd.DataFrame(employees)

df["Bonus"] = df["Salary"] * 0.10

df

     Name  Age Dept  Salary   Bonus
0   Rahul   25   DS   70000  7000.0
1  Ganraj   28   DE   80000  8000.0
2   Priya   26   DS   65000  6500.0
3    Neha   30   ML   90000  9000.0

#### 3. Rename columns: 'Dept' → 'Department', 'Salary' → 'CTC'.

In [129]:
# Use rename() for selective changes.
df.rename( columns={
           "Dept": "Department",
           "Salary": "CTC" }, inplace=True)
df

     Name  Age Department    CTC   Bonus
0   Rahul   25         DS  70000  7000.0
1  Ganraj   28         DE  80000  8000.0
2   Priya   26         DS  65000  6500.0
3    Neha   30         ML  90000  9000.0

### Exercise Set 2 — Indexing & Selection
```
4. Using .loc, select employees whose Salary > 60000 AND Dept == 'DS'.
5. Using .iloc, select rows 1-3 and columns 0-2.
6. Set 'Name' as index and access data for a specific employee.
```

#### 4. Using .loc, select employees whose Salary > 60000 AND Dept == 'DS'.

In [130]:
# loc is preferred because you're expressing salary condition,
# not row positions.

# .loc -> accepts a Boolean mask
# loc = labels + condition

df.loc[(df["CTC"] > 60000) & (df["Department"] == "DS")]

    Name  Age Department    CTC   Bonus
0  Rahul   25         DS  70000  7000.0
2  Priya   26         DS  65000  6500.0

In [131]:
df.columns.tolist()

['Name', 'Age', 'Department', 'CTC', 'Bonus']

#### 5. Using .iloc, select rows 1-3 and columns 0-2.

In [132]:
df.iloc[1:4, 0:3]

     Name  Age Department
1  Ganraj   28         DE
2   Priya   26         DS
3    Neha   30         ML

#### 6. Set 'Name' as index and access data for a specific employee.

In [133]:
df = df.set_index("Name")

df.loc["Rahul"]

Age               25
Department        DS
CTC            70000
Bonus         7000.0
Name: Rahul, dtype: object

### Exercise Set 3 — Data Cleaning
```
7. Given a DataFrame with missing values, fill numeric NaN with column mean,
   and string NaN with 'Unknown'.
8. Find and remove duplicate rows.
9. Convert an 'Age' column stored as strings to integers.
10. Use str.strip() and str.title() to clean a messy 'Name' column.
```

#### 7. Given a DataFrame with missing values, fill numeric NaN with column mean, and string NaN with 'Unknown'.

In [134]:
# fill numeric NaN with column mean
num_cols = df.select_dtypes(include="number").columns

df[num_cols] = df[num_cols].fillna(
    df[num_cols].mean())

df[num_cols]

        Age    CTC   Bonus
Name
Rahul    25  70000  7000.0
Ganraj   28  80000  8000.0
Priya    26  65000  6500.0
Neha     30  90000  9000.0

In [135]:
# fill string NaN with 'Unknown'
obj_cols = df.select_dtypes(include="object").columns

df[obj_cols] = df[obj_cols].fillna("Unknown")

df[obj_cols]

       Department
Name
Rahul          DS
Ganraj         DE
Priya          DS
Neha           ML

#### 8. Find and remove duplicate rows.

In [136]:
# Remove duplicates
df = df.drop_duplicates()
df

        Age Department    CTC   Bonus
Name
Rahul    25         DS  70000  7000.0
Ganraj   28         DE  80000  8000.0
Priya    26         DS  65000  6500.0
Neha     30         ML  90000  9000.0

In [137]:
df.duplicated()

Name
Rahul     False
Ganraj    False
Priya     False
Neha      False
dtype: bool

#### 9. Convert an 'Age' column stored as strings to integers.

In [138]:
df["Age"] = df["Age"].astype(int)
df

        Age Department    CTC   Bonus
Name
Rahul    25         DS  70000  7000.0
Ganraj   28         DE  80000  8000.0
Priya    26         DS  65000  6500.0
Neha     30         ML  90000  9000.0

#### 10. Use str.strip() and str.title() to clean a messy 'Name' column.

In [139]:
print(df.columns.tolist())

['Age', 'Department', 'CTC', 'Bonus']

In [140]:
df1 = pd.DataFrame({
    "Name": [" Ganesh ", "Manish", "Sonu"]
})

df1["Name"] = df1["Name"].str.strip().str.title()

print(df1)

     Name
0  Ganesh
1  Manish
2    Sonu

### Exercise Set 4 — Manipulation & GroupBy
```
11. Filter employees with Score > 80, sort by Score descending.
12. Use groupby to find:
    - Count per Department
    - Mean Salary per Department
    - Top scorer per Department
13. Create a pivot table showing mean Salary by Dept × City.
```

#### 11. Filter employees with Score > 80, sort by Score descending.

In [141]:
result = ( df.loc[df["Age"] > 20]
      .sort_values(by="Age", ascending=False))
result

        Age Department    CTC   Bonus
Name
Neha     30         ML  90000  9000.0
Ganraj   28         DE  80000  8000.0
Priya    26         DS  65000  6500.0
Rahul    25         DS  70000  7000.0

#### 12. Use groupby to find:
    - Count per Department
    - Mean Salary per Department
    - Top scorer per Department

In [142]:
# Count per Department:-
df.groupby("Department").size()

Department
DE    1
DS    2
ML    1
dtype: int64

In [143]:
# Mean Salary per Department
df.groupby("Department")["CTC"].mean()

Department
DE    80000.0
DS    67500.0
ML    90000.0
Name: CTC, dtype: float64

In [144]:
# Top Scorer per Department
idx = df.groupby("Department")["CTC"].idxmax()

top_scorers = df.loc[idx]
top_scorers

        Age Department    CTC   Bonus
Name
Ganraj   28         DE  80000  8000.0
Rahul    25         DS  70000  7000.0
Neha     30         ML  90000  9000.0

#### 13. Create a pivot table showing mean Salary by Dept × City.

In [145]:
pivot = pd.pivot_table(
    df,
    values="CTC",
    index="Department",
    columns="Age",
    aggfunc="mean"
)

pivot

Age              25       26       28       30
Department
DE              NaN      NaN  80000.0      NaN
DS          70000.0  65000.0      NaN      NaN
ML              NaN      NaN      NaN  90000.0

In [146]:
df.groupby(
    ["Department", "Age"]
)["CTC"].mean().unstack()

Age              25       26       28       30
Department
DE              NaN      NaN  80000.0      NaN
DS          70000.0  65000.0      NaN      NaN
ML              NaN      NaN      NaN  90000.0

### Exercise Set 5 — DateTime & I/O
```
14. Parse a list of date strings, extract year/month/weekday.
15. Calculate the number of days between two date columns.
16. Read a CSV, optimize dtypes, compare memory before/after.
```

#### 14. Parse a list of date strings, extract year/month/weekday.

- Date parsing -> Raw data rarely arrives as datetime.
- .dt accessor -> Vectorized datetime operations.
- Feature engineering -> Extracting useful time features.

In [147]:
dates = pd.Series([
    "2024-01-15",
    "2024-06-10",
    "2024-12-25"
])

dt = pd.to_datetime(dates)

result = pd.DataFrame({
    "Year": dt.dt.year,
    "Month": dt.dt.month,
    "Weekday": dt.dt.day_name()
})

result

   Year  Month    Weekday
0  2024      1     Monday
1  2024      6     Monday
2  2024     12  Wednesday

#### 15. Calculate the number of days between two date columns.

In [148]:
df = pd.DataFrame({
    "StartDate": ["2024-01-01","2024-02-10"],
    "EndDate": ["2024-01-15","2024-03-01"]
})

df

    StartDate     EndDate
0  2024-01-01  2024-01-15
1  2024-02-10  2024-03-01

In [149]:
# number of days between two date columns:-
df["StartDate"] = pd.to_datetime(df["StartDate"])
df["EndDate"] = pd.to_datetime(df["EndDate"])

df["Days"] = (df["EndDate"] - df["StartDate"]).dt.days

df["Days"]

0    14
1    20
Name: Days, dtype: int64

#### 16. Read a CSV, optimize dtypes, compare memory before/after.

In [151]:
# Read a csv file
df = pd.read_csv("employees.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [152]:
# Check a memory usage -> before 
before = df.memory_usage(deep=True).sum()
before

np.int64(366602)

In [153]:
# Optimize dtypes
# Integer Downcasting

df["Salary"] = pd.to_numeric(
    df["Salary"],
    downcast="integer")

df["Salary"]

0       97308
1       61933
2      130590
3      138705
4      101004
        ...
995    132483
996     42392
997     96914
998     60500
999    129949
Name: Salary, Length: 1000, dtype: int32

In [154]:
# Float Downcasting
df["Salary"] = pd.to_numeric(
    df["Salary"],
    downcast="float"
)
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308.0,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705.0,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483.0,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392.0,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914.0,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500.0,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949.0,10.169,True,Sales

In [155]:
# Convert Low-Cardinality Strings
df["Team"] = (
    df["Team"]
    .astype("category")
)

df["Team"]

0                 Marketing
1                       NaN
2                   Finance
3                   Finance
4           Client Services
               ...
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: category
Categories (10, object): ['Business Development', 'Client Services', 'Distribution', 'Engineering', ..., 'Legal', 'Marketing', 'Product', 'Sales']

In [156]:
# Compare Memory
after = df.memory_usage(deep=True).sum()

print("Before:", before)
print("After :", after)

reduction = (
    (before - after) / before * 100
)

print(f"Reduced by {reduction:.2f}%")

Before: 366602
After : 298415
Reduced by 18.60%

In [157]:
# ── Exercise Solutions Scaffold (try before looking!) ─────────────

# Exercise 1 — Series with student names as index
marks = pd.Series([85, 92, 78, 95, 60],
                  index=["Alice","Bob","Charlie","Diana","Eve"],
                  name="Marks")
print("Ex1 — Student marks:\n", marks)

# Exercise 2 — DataFrame + Bonus column
employees_ex = pd.DataFrame([
    {"Name":"Alice",   "Age":25, "Dept":"DS",  "Salary":70000},
    {"Name":"Bob",     "Age":30, "Dept":"ML",  "Salary":80000},
    {"Name":"Charlie", "Age":22, "Dept":"DS",  "Salary":65000},
    {"Name":"Diana",   "Age":28, "Dept":"AI",  "Salary":90000},
])
employees_ex["Bonus"] = employees_ex["Salary"] * 0.10
print("\nEx2 — Employees with Bonus:\n", employees_ex)

# Exercise 3 — Rename columns
employees_ex.rename(columns={"Dept":"Department","Salary":"CTC"}, inplace=True)
print("\nEx3 — Renamed columns:", employees_ex.columns.tolist())

# Exercise 4 — loc conditional selection
print("\nEx4 — CTC > 70000 AND Department == 'DS':")
print(employees_ex.loc[(employees_ex["CTC"] > 70000) & (employees_ex["Department"] == "DS")])

# Exercise 12 — GroupBy
df_ex12 = pd.DataFrame({
    "Name"  : ["A","B","C","D","E","F"],
    "Dept"  : ["DS","ML","DS","ML","DS","AI"],
    "Score" : [88,92,75,95,80,70],
    "Salary": [70000,80000,65000,90000,75000,60000]
})
print("\nEx12 — GroupBy results:")
print(df_ex12.groupby("Dept").agg(
    count      =("Name","count"),
    mean_salary=("Salary","mean"),
    top_score  =("Score","max")
))

Ex1 — Student marks:
 Alice      85
Bob        92
Charlie    78
Diana      95
Eve        60
Name: Marks, dtype: int64

Ex2 — Employees with Bonus:
       Name  Age Dept  Salary   Bonus
0    Alice   25   DS   70000  7000.0
1      Bob   30   ML   80000  8000.0
2  Charlie   22   DS   65000  6500.0
3    Diana   28   AI   90000  9000.0

Ex3 — Renamed columns: ['Name', 'Age', 'Department', 'CTC', 'Bonus']

Ex4 — CTC > 70000 AND Department == 'DS':
Empty DataFrame
Columns: [Name, Age, Department, CTC, Bonus]
Index: []

Ex12 — GroupBy results:
      count  mean_salary  top_score
Dept
AI        1      60000.0         70
DS        3      70000.0         88
ML        2      85000.0         95

---
## Summary — Pandas Cheat Sheet

### Core Operations at a Glance

| Task | Code |
|------|------|
| Create DataFrame | `pd.DataFrame(data)` |
| Read CSV | `pd.read_csv("file.csv")` |
| View shape | `df.shape` |
| Select column | `df["col"]` or `df.col` |
| Select rows (label) | `df.loc[label]` |
| Select rows (position) | `df.iloc[pos]` |
| Filter rows | `df[df["col"] > val]` |
| Add column | `df["new"] = values` |
| Rename column | `df.rename(columns={old:new})` |
| Drop column | `df.drop(columns=["col"])` |
| Sort | `df.sort_values("col")` |
| GroupBy | `df.groupby("col").agg(...)` |
| Pivot table | `pd.pivot_table(df, ...)` |
| Merge | `pd.merge(df1, df2, on="key")` |
| Concatenate | `pd.concat([df1, df2])` |
| Missing values | `df.fillna(val)` / `df.dropna()` |
| Convert type | `df["col"].astype(dtype)` |
| DateTime parse | `pd.to_datetime(series)` |
| String ops | `df["col"].str.upper()` |
| Apply function | `df["col"].apply(func)` |
| Memory usage | `df.memory_usage(deep=True)` |

---

### What's Next?
- **Matplotlib / Seaborn** — Visualize your DataFrame data
- **Scikit-learn** — Feed cleaned DataFrames into ML models
- **SQL with Pandas** — `pd.read_sql()` for database integration
- **Dask / Polars** — For truly massive datasets beyond RAM limits

---
*Notebook created by Senior AIML Instructor | Pandas Complete Guide*  
*pandas version: {}*