# 100 Pandas Practical Questions
> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

---

## Section 1: Basics & Series (Q1–Q20)

---

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

---

In [6]:
import pandas as pd
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

---

In [7]:
# Dictionary keys automatically become row labels.
data = {
    "Rahul": 95,
    "Ganraj": 70,
    "Pooja": 88
}

s = pd.Series(data)
s

Rahul     95
Ganraj    70
Pooja     88
dtype: int64

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

---

In [8]:
# For a single value
s["Rahul"]

np.int64(95)

In [9]:
# For a multiple values:-
s[["Rahul", "Ganraj"]]

Rahul     95
Ganraj    70
dtype: int64

In [10]:
# For a range
s["Rahul":"Pooja"]

Rahul     95
Ganraj    70
Pooja     88
dtype: int64

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

---

In [11]:
print(s + 5)
print(s - 3)
print(s * 10)
print(s / 2)
print(s // 2)
print(s % 2)
print(s ** 2)

Rahul     100
Ganraj     75
Pooja      93
dtype: int64
Rahul     92
Ganraj    67
Pooja     85
dtype: int64
Rahul     950
Ganraj    700
Pooja     880
dtype: int64
Rahul     47.5
Ganraj    35.0
Pooja     44.0
dtype: float64
Rahul     47
Ganraj    35
Pooja     44
dtype: int64
Rahul     1
Ganraj    0
Pooja     0
dtype: int64
Rahul     9025
Ganraj    4900
Pooja     7744
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

---

In [12]:
print(s.mean())
print(s.min())
print(s.max())
print(s.sum())
print(s.median())
print(s.std())

84.33333333333333
70
95
253
88.0
12.897028081435401

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

---

In [13]:
# Boolean masking
s[s > 50]

Rahul     95
Ganraj    70
Pooja     88
dtype: int64

In [14]:
# & conditions:-
s[(s > 50) & (s < 90)]

Ganraj    70
Pooja     88
dtype: int64

In [15]:
# or conditions:-
s[(s > 50) | (s < 90)]

Rahul     95
Ganraj    70
Pooja     88
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

---

In [16]:
import numpy as np

s = pd.Series([10, 0, 25, 0, 40])

s = s.replace(0, np.nan)

print(s)

0    10.0
1     NaN
2    25.0
3     NaN
4    40.0
dtype: float64

In [17]:
# Multiple replacement
s = pd.Series(["M", "F", "M", "F", "M"])

s = s.replace({
    "M": "Male",
    "F": "Female"
})

print(s)

0      Male
1    Female
2      Male
3    Female
4      Male
dtype: object

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

---

In [18]:
s1 = pd.Series([10, 20, 30])
s1 = s1.astype("category")
s1

0    10
1    20
2    30
dtype: category
Categories (3, int64): [10, 20, 30]

In [19]:
s1.astype(float)

0    10.0
1    20.0
2    30.0
dtype: float64

In [20]:
s1.astype(int)

0    10
1    20
2    30
dtype: int64

In [21]:
s.astype("category")

0      Male
1    Female
2      Male
3    Female
4      Male
dtype: category
Categories (2, object): ['Female', 'Male']

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

---

In [22]:
s.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [23]:
# Count missing values:-
s.isnull().sum()

np.int64(0)

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

---

In [24]:
# For constant
s.fillna(0)

0      Male
1    Female
2      Male
3    Female
4      Male
dtype: object

In [26]:
print("Data type:", s.dtype)
print("Sample values:\n", s.head())

Data type: object
Sample values:
 0      Male
1    Female
2      Male
3    Female
4      Male
dtype: object

In [27]:
# 1. Check what the mode is:
print(s.mode())
# Output might be: 0    Male

# 2. Fill missing values with the mode:
s = s.fillna(s.mode()[0])

0    Male
dtype: object

In [ ]:
# For forward fill
s.ffill()

0    10.0
1    10.0
2    25.0
3    25.0
4    40.0
dtype: float64

In [28]:
# for backward fill
s.bfill()

0      Male
1    Female
2      Male
3    Female
4      Male
dtype: object

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

---

In [29]:
data = [
    ["Rahul", 95],
    ["Ganraj", 90]
]

df = pd.DataFrame(
    data,
    columns=["Name", "Score"]
)

df

     Name  Score
0   Rahul     95
1  Ganraj     90

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

---

In [30]:
# Dictionary keys become columns.

df = pd.DataFrame({
    "Name": ["Rahul", "Ganraj"],
    "Score": [95, 70]
})

df

     Name  Score
0   Rahul     95
1  Ganraj     70

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

---

In [31]:
# DataFrame from list of dictionaries

df = pd.DataFrame([
    {"Name": "Rahul", "Score": 95},
    {"Name": "Amit", "Score": 70}
])

df

    Name  Score
0  Rahul     95
1   Amit     70

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

---

In [32]:
print(df.shape) # Rows * columns
print(df.columns)
print(df.dtypes)
print(df.info())  # Full summary
print(df.describe()) # Statistics

(2, 2)
Index(['Name', 'Score'], dtype='object')
Name     object
Score     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Score   2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes
None
          Score
count   2.00000
mean   82.50000
std    17.67767
min    70.00000
25%    76.25000
50%    82.50000
75%    88.75000
max    95.00000

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

---

In [33]:
df["Score"]

0    95
1    70
Name: Score, dtype: int64

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

---

In [34]:
df = pd.DataFrame({
    "Name": ["Rahul", "Ganraj"],
    "Score": [90, 85],
    "City": ["Pune", "Mumbai"]
})

df[["Name", "Score"]]

     Name  Score
0   Rahul     90
1  Ganraj     85

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

---

In [35]:
df["Country"] = "India"
df

     Name  Score    City Country
0   Rahul     90    Pune   India
1  Ganraj     85  Mumbai   India

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`.

> The Series index must align with the DataFrame index.

---

In [36]:
df["Rank"] = pd.Series([1, 2])

In [37]:
df["Rank"] = pd.Series(
    [1, 2],
    index=[0, 1]
)
df

     Name  Score    City Country  Rank
0   Rahul     90    Pune   India     1
1  Ganraj     85  Mumbai   India     2

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

---

In [38]:
df.rename(columns={"Score": "Marks"})

     Name  Marks    City Country  Rank
0   Rahul     90    Pune   India     1
1  Ganraj     85  Mumbai   India     2

In [39]:
# By using inplace
df.rename(
    columns={"Score":"Marks"},
    inplace=True
)
df

     Name  Marks    City Country  Rank
0   Rahul     90    Pune   India     1
1  Ganraj     85  Mumbai   India     2

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

---

In [40]:
# Use a mapping dictionary
df.rename(
    columns={
        "Name": "Employee_Name",
        "Score": "Marks",
        "Dept": "Department"
    }
)

df

     Name  Marks    City Country  Rank
0   Rahul     90    Pune   India     1
1  Ganraj     85  Mumbai   India     2

## Section 2: Indexing, Selection & Slicing (Q21–Q40)

---

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

---

In [41]:
# loc performs label-based row selection.

df = pd.DataFrame(
    {"Score":[90,85,95]},
    index=["Rahul","Ganraj","Amit"]
)

df.loc["Rahul"]

Score    90
Name: Rahul, dtype: int64

In [42]:
df.loc["Rahul":"Ganraj"]

        Score
Rahul      90
Ganraj     85

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

---

In [43]:
print(df.iloc[0])   # for first row

print(df.iloc[1:4])  # for rows 1-3

Score    90
Name: Rahul, dtype: int64
        Score
Ganraj     85
Amit       95

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

---

In [44]:
df.loc["Rahul", "Score"]

np.int64(90)

In [45]:
df.iloc[0]

Score    90
Name: Rahul, dtype: int64

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

---

In [46]:
# Using loc (Label-Based)

df.loc[['Rahul', 'Ganraj'], ['Score']]

        Score
Rahul      90
Ganraj     85

In [47]:
# Using iloc (Position-Based)
df.iloc[[0, 2]]

       Score
Rahul     90
Amit      95

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

---

In [48]:
df

        Score
Rahul      90
Ganraj     85
Amit       95

In [49]:
df.loc[df['Score'] > 50, ['Score']]

        Score
Rahul      90
Ganraj     85
Amit       95

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

---

In [50]:
# Label-based
df.loc["Rahul":"Amit"]

        Score
Rahul      90
Ganraj     85
Amit       95

In [51]:
# Position-Based
df.iloc[0:4]

        Score
Rahul      90
Ganraj     85
Amit       95

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

---

In [52]:
df.loc[:, "Rahul":"Score"]
df

        Score
Rahul      90
Ganraj     85
Amit       95

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

---

In [53]:
df.iloc[:, 1:4]

Empty DataFrame
Columns: []
Index: [Rahul, Ganraj, Amit]

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

---

In [54]:
df = pd.DataFrame({
    'Name': ['Rahul', 'Ganraj', 'Neha', 'Priya'],
    'Marks': [95, 70, 88, 70],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Nashik']
})

result = df.loc[df['Marks'] > 80, ['Name', 'City']]

print(result)

    Name   City
0  Rahul   Pune
2   Neha  Delhi

In [56]:
df

     Name  Marks    City
0   Rahul     95    Pune
1  Ganraj     70  Mumbai
2    Neha     88   Delhi
3   Priya     70  Nashik

In [55]:
print(df.columns.tolist())

['Name', 'Marks', 'City']

In [57]:
# Using loc (Label-Based + Condition-Based)
df.loc[df['Marks'] > 60, ['Name', 'Marks']]

     Name  Marks
0   Rahul     95
1  Ganraj     70
2    Neha     88
3   Priya     70

In [58]:
df.loc[df["Name"]=="Rahul",
       ["Name","Marks"]]

    Name  Marks
0  Rahul     95

In [59]:
df.iloc[0:2,[0,1]]

     Name  Marks
0   Rahul     95
1  Ganraj     70

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

---

In [60]:
print(df.columns.tolist())

['Name', 'Marks', 'City']

In [61]:
df = df.set_index("Name", inplace=True)

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

---

In [64]:
import pandas as pd

# 1. Create a sample DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai"],
    "Marks": [85, 90, 85, 95],
    "Age": [20, 21, 20, 22]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
print()

# 2. Set MultiIndex on ["Marks", "City"]
df_multi = df.set_index(["Marks", "City"])
print("With MultiIndex:\n", df_multi)

Original DataFrame:
       Name    City  Marks  Age
0    Alice   Delhi     85   20
1      Bob  Mumbai     90   21
2  Charlie   Delhi     85   20
3    David  Mumbai     95   22

With MultiIndex:
                  Name  Age
Marks City
85    Delhi     Alice   20
90    Mumbai      Bob   21
85    Delhi   Charlie   20
95    Mumbai    David   22

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

---

In [ ]:
df.reset_index()

   index   Name  Marks Country  new_col
0      0  Rahul     95   India     1000
1      1   Amit     70   India     2000

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

---

In [ ]:
# All index levels become columns.
df.reset_index()

   index   Name  Marks Country  new_col
0      0  Rahul     95   India     1000
1      1   Amit     70   India     2000

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

---

In [ ]:
df.reset_index()

   index    Name  Marks    City
0      0   Rahul     95    Pune
1      1  Ganraj     70  Mumbai
2      2    Neha     88   Delhi
3      3   Priya     70  Nashik

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

---

In [ ]:
df.reset_index(drop=True)

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

---

In [ ]:
df.loc["Rahul"]

Marks      95
City     Pune
Name: Rahul, dtype: object

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

---

In [ ]:
df.iloc[0]

Name     Rahul
Marks       95
City      Pune
Name: 0, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

---

In [ ]:
df.head(10)

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

---

In [ ]:
df.tail(10)

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

---

In [ ]:
# For random rows
df.sample(n=2)

       Marks    City
Name
Rahul     95    Pune
Priya     70  Nashik

In [ ]:
# for 20% of rows

df.sample(frac=0.2)

Empty DataFrame
Columns: [Name, Marks, Country, new_col]
Index: []

In [ ]:
#  Set random_state for reproducibility.

df.sample(n=2,
          random_state=42)

        Marks    City
Name
Ganraj     70  Mumbai
Priya      70  Nashik

## Section 3: Data Cleaning (Q41–Q60)

---

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

---

In [ ]:
# isnull() creates a missing-value map of your dataset.
df.isnull

<bound method DataFrame.isnull of     Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000>

In [ ]:
# Use .isnull().sum() for column-wise counts
df.isnull().sum()

Name       0
Marks      0
Country    0
new_col    0
dtype: int64

In [ ]:
df.isnull().any()   # to check if any exists

Name       False
Marks      False
Country    False
new_col    False
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

---

In [ ]:
# drops any row with a NaN
df.dropna()

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

In [ ]:
# Use axis=1 for columns, subset=["col"] for specific columns
df.dropna(subset=["Marks"])

        Marks    City
Name
Rahul      95    Pune
Ganraj     70  Mumbai
Neha       88   Delhi
Priya      70  Nashik

In [ ]:
# removes only rows where Salary is missing.
df.dropna(thresh = 4)

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

---

In [ ]:
df.fillna(0)

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

In [ ]:
df

        Marks    City
Name
Rahul      95    Pune
Ganraj     70  Mumbai
Neha       88   Delhi
Priya      70  Nashik

In [ ]:
df["City"].fillna("Unknown")

Name
Rahul       Pune
Ganraj    Mumbai
Neha       Delhi
Priya     Nashik
Name: City, dtype: object

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

---

In [ ]:
print(df.columns.tolist())

['Marks', 'City']

In [ ]:
df["Marks"].fillna(df["Marks"].mean())

Name
Rahul     95
Ganraj    70
Neha      88
Priya     70
Name: Marks, dtype: int64

In [ ]:
df["Marks"] = df["Marks"].fillna(df["Marks"].median())
df["Marks"]

Name
Rahul     95
Ganraj    70
Neha      88
Priya     70
Name: Marks, dtype: int64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

---

In [ ]:
df.ffill()

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

In [ ]:
df.bfill()

    Name  Marks Country  new_col
0  Rahul     95   India     1000
1   Amit     70   India     2000

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

---

In [ ]:
df["Marks"] = df["Marks"].astype(int)
df["Marks"]

Name
Rahul     95
Ganraj    70
Neha      88
Priya     70
Name: Marks, dtype: int64

In [ ]:
# Convert it into string
df["Marks"] = df["Marks"].astype(str)

In [ ]:
# Convert to Category
# df["Name"] = df["Name"].astype("category")

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

---

In [ ]:
df["City"].str.lower()

Name
Rahul       pune
Ganraj    mumbai
Neha       delhi
Priya     nashik
Name: City, dtype: object

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

---

In [ ]:
df["Name"].str.strip()

0    Rahul
1     Amit
Name: Name, dtype: object

In [ ]:
df["Name"] = df["Name"].str.strip()

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

---

In [ ]:
df

     Name  Marks    City
0   Rahul     95    Pune
1  Ganraj     70  Mumbai
2    Neha     88   Delhi
3   Priya     70  Nashik

In [ ]:
df["City"] = df["City"].str.replace("Mumbai", "Bombay")
df["City"]

0      Pune
1    Bombay
2     Delhi
3    Nashik
Name: City, dtype: object

In [ ]:
df["City"] = df["City"].str.replace(r".*i$", "Indian City", regex=True)
df["City"]

0      PIndian CitynIndian City
1    BIndian CitymbIndian Cityy
2     DIndian CitylhIndian City
3    NIndian CityshIndian Cityk
Name: City, dtype: object

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

---

In [ ]:
# Extract first 3 characters
df["Name"].str[:3]

0    Rah
1    Gan
2    Neh
3    Pri
Name: Name, dtype: object

In [ ]:
# Extract Last 3 Characters
df["City"].str[-3:]

0    ity
1    tyy
2    ity
3    tyk
Name: City, dtype: object

In [ ]:
# Extract Characters from Position 1 to 4
df["Name"].str[1:4]

0    ahu
1    anr
2    eha
3    riy
Name: Name, dtype: object

In [ ]:
# Split using a delimiter
# Number of values = Number of rows

df["Email"] = [
    "rahul@gmail.com",
    "ganraj@yahoo.com",
    "neha@outlook.com",
    "priya@gmail.com"
]

df["Email"]

0     rahul@gmail.com
1    ganraj@yahoo.com
2    neha@outlook.com
3     priya@gmail.com
Name: Email, dtype: object

In [ ]:
# For Extracting Username
df["Email"].str.split("@").str[0]

0     rahul
1    ganraj
2      neha
3     priya
Name: Email, dtype: object

In [ ]:
# Extract domain:-
df["Email"].str.split("@").str[1]

0      gmail.com
1      yahoo.com
2    outlook.com
3      gmail.com
Name: Email, dtype: object

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

---

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Marks, City, Email]
Index: []

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

---

In [ ]:
df.drop_duplicates()

     Name  Marks                        City             Email
0   Rahul     95    PIndian CitynIndian City   rahul@gmail.com
1  Ganraj     70  BIndian CitymbIndian Cityy  ganraj@yahoo.com
2    Neha     88   DIndian CitylhIndian City  neha@outlook.com
3   Priya     70  NIndian CityshIndian Cityk   priya@gmail.com

In [ ]:
df.drop_duplicates(subset=["Name"])

     Name  Marks                        City             Email
0   Rahul     95    PIndian CitynIndian City   rahul@gmail.com
1  Ganraj     70  BIndian CitymbIndian Cityy  ganraj@yahoo.com
2    Neha     88   DIndian CitylhIndian City  neha@outlook.com
3   Priya     70  NIndian CityshIndian Cityk   priya@gmail.com

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

---

In [ ]:
df.rename(index={0: "R1", 1: "N1"})

      Name  Marks                        City             Email
R1   Rahul     95    PIndian CitynIndian City   rahul@gmail.com
N1  Ganraj     70  BIndian CitymbIndian Cityy  ganraj@yahoo.com
2     Neha     88   DIndian CitylhIndian City  neha@outlook.com
3    Priya     70  NIndian CityshIndian Cityk   priya@gmail.com

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

---

In [ ]:
df["City"] = (
    df["City"]
      .str.strip()
      .str.lower()
)

In [ ]:
df["City"] = df["City"].replace({
    "Mumbai": "Bombay",
    "Delhi": "Capital"
})

df["City"]

0       Pune
1     Bombay
2    Capital
3     Nashik
Name: City, dtype: object

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

---

In [ ]:
df.replace("Pune", "PUNE")

     Name  Marks     City
0   Rahul     95     PUNE
1  Ganraj     70   Bombay
2    Neha     88  Capital
3   Priya     70   Nashik

In [ ]:
# Dictionary Replacement
df.replace({
    "PUNE": "Pune",
    "Bombay": "MUMBAI"
})

     Name  Marks     City
0   Rahul     95     Pune
1  Ganraj     70   MUMBAI
2    Neha     88  Capital
3   Priya     70   Nashik

In [ ]:
# Column-specific replacement:-
df.replace({
    "City": {
        "Pune": "PUNE",
        "MUMBAI": "Bombay"
    }
})

     Name  Marks     City
0   Rahul     95     PUNE
1  Ganraj     70   Bombay
2    Neha     88  Capital
3   Priya     70   Nashik

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

---

In [ ]:
# IQR Method:- (Skewed data)
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Marks"] < lower) |
    (df["Marks"] > upper)
]

outliers

Empty DataFrame
Columns: [Name, Marks, City]
Index: []

In [ ]:
# z-score:- Normal Distribution
from scipy.stats import zscore

z = zscore(df["Marks"])

df[abs(z) > 3]

Empty DataFrame
Columns: [Name, Marks, City]
Index: []

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

---

In [ ]:
df["Marks"] = df["Marks"].clip(
    lower=0,
    upper=100)

df["Marks"]

0    95
1    70
2    88
3    70
Name: Marks, dtype: int64

In [ ]:
# using IQR bounds
df["Marks"] = df["Marks"].clip(
    lower=lower,
    upper=upper)

df["Marks"]

0    95
1    70
2    88
3    70
Name: Marks, dtype: int64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

---

In [ ]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

---

In [ ]:
df["Marks"] = pd.to_numeric(
    df["Marks"],
    errors="coerce"
)

df["Marks"]

0    95
1    70
2    88
3    70
Name: Marks, dtype: int64

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

---

In [ ]:
df["Name"] = df["Name"].str.replace(
    r"[^a-zA-Z0-9 ]",
    "",
    regex=True
)

df["Name"]

0     Rahul
1    Ganraj
2      Neha
3     Priya
Name: Name, dtype: object

## Section 4: Data Manipulation (Q61–Q80)

---

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

---

In [ ]:
df[(df["Marks"] > 80) & (df["City"] == "Pune")]

    Name  Marks  City
0  Rahul     95  Pune

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

---

In [ ]:
df[(df["Marks"] > 90) | (df["City"] == "Mumbai")]

     Name  Marks    City
0   Rahul     95    Pune
1  Ganraj     70  Mumbai

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

---

In [ ]:
df[~(df["City"] == "Pune")]

     Name  Marks    City
1  Ganraj     70  Mumbai
2    Neha     88   Delhi
3   Priya     70  Nashik

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

---

In [ ]:
df.sort_values("Marks")  # Ascending

     Name  Marks    City
1  Ganraj     70  Mumbai
3   Priya     70  Nashik
2    Neha     88   Delhi
0   Rahul     95    Pune

In [ ]:
# For Descending Order
df.sort_values("Marks", ascending=False)

     Name  Marks    City
0   Rahul     95    Pune
2    Neha     88   Delhi
1  Ganraj     70  Mumbai
3   Priya     70  Nashik

In [ ]:
# Multi-column sort
df.sort_values(
    by=["City", "Marks"],
    ascending=[True, False]
)

     Name  Marks    City
2    Neha     88   Delhi
1  Ganraj     70  Mumbai
3   Priya     70  Nashik
0   Rahul     95    Pune

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

---

In [ ]:
df.sort_index()

     Name  Marks    City
0   Rahul     95    Pune
1  Ganraj     70  Mumbai
2    Neha     88   Delhi
3   Priya     70  Nashik

In [ ]:
# For sorting column alphabetically
df.sort_index(axis=1)

     City  Marks    Name
0    Pune     95   Rahul
1  Mumbai     70  Ganraj
2   Delhi     88    Neha
3  Nashik     70   Priya

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

---

In [ ]:
df["Bonus"] = df["Marks"] * 10
df["Bonus"]

0    950
1    700
2    880
3    700
Name: Bonus, dtype: int64

In [ ]:
# Chainable version:-
df = df.assign(
    Bonus=lambda x: x["Marks"] * 10
)
df

     Name  Marks    City  Bonus
0   Rahul     95    Pune    950
1  Ganraj     70  Mumbai    700
2    Neha     88   Delhi    880
3   Priya     70  Nashik    700

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

---

In [ ]:
df.drop(columns=["City"])

     Name  Marks  Bonus
0   Rahul     95    950
1  Ganraj     70    700
2    Neha     88    880
3   Priya     70    700

In [ ]:
# For dropping multiple columns:-
df.drop(columns=["City", "Bonus"])

     Name  Marks
0   Rahul     95
1  Ganraj     70
2    Neha     88
3   Priya     70

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

> removes rows by label & not by position
---

In [ ]:
# Removes rows with index labels 0 & 2
df.drop(index=[0, 2])

     Name  Marks    City  Bonus
1  Ganraj     70  Mumbai    700
3   Priya     70  Nashik    700

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

---

In [ ]:
# Dictionary Mapping:- 
# map() -> 1 column transformation

df["Grade"] = df["City"].map({
    "Pune": 1,
    "Mumbai": 2,
    "Delhi": 3 })
df["Grade"]

0    1.0
1    2.0
2    3.0
3    NaN
Name: Grade, dtype: float64

In [ ]:
# Function Mapping:-
df["Marks"] = df["Marks"].map(lambda x: x + 5)

df["Marks"]

0    105
1     80
2     98
3     80
Name: Marks, dtype: int64

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

---

In [ ]:
# For a Series
df["Marks"].apply( lambda x: x * 2 )

0    210
1    160
2    196
3    160
Name: Marks, dtype: int64

In [ ]:
# For Column-wise:-
df.apply(lambda col: col.count())

Name     4
Marks    4
City     4
Rank     4
Flag     4
dtype: int64

In [ ]:
# Row-wise
df.apply(lambda row: row["Marks"] * 2, axis=1)

0    190
1    140
2    176
3    140
dtype: int64

In [ ]:
# For Row-wise:-
df.apply( lambda row: row["Marks"] * 2, axis=1 )

0    210
1    160
2    196
3    160
dtype: int64

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

---

In [ ]:
# map() -> Series / DataFrame
# apply() -> Row / Column
# applymap() -> Every cell

# In pandas >= 2.1
df.map( lambda x: str(x).upper())

     Name Marks    City
0   RAHUL    95    PUNE
1  GANRAJ    70  MUMBAI
2    NEHA    88   DELHI
3   PRIYA    70  NASHIK

In [ ]:
# Older Pandas
df.applymap(lambda x: str(x).upper())

C:\Users\rahul\AppData\Local\Temp\ipykernel_31812\1828984756.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: str(x).upper())

     Name Marks    City
0   RAHUL    95    PUNE
1  GANRAJ    70  MUMBAI
2    NEHA    88   DELHI
3   PRIYA    70  NASHIK

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

---

In [ ]:
# Chain Multiple Operations:-
df = (df.copy().query("Marks > 80")
      .sort_values("Marks", ascending=False)
      .assign(Grade=lambda x: x["Marks"] / 10)
      .reset_index(drop=True)
)
df

    Name  Marks   City  Grade
0  Rahul     95   Pune    9.5
1   Neha     88  Delhi    8.8

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

---

In [ ]:
df["Marks_norm"] = (
    df["Marks"] - df["Marks"].min()
) / (
    df["Marks"].max() - df["Marks"].min()
)

df["Marks_norm"]

0    1.00
1    0.00
2    0.72
3    0.00
Name: Marks_norm, dtype: float64

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

---

In [ ]:
# Scale Numerical Data(z-score)

df["Marks_z"] = (
    df["Marks"] - df["Marks"].mean()
) / df["Marks"].std()

df["Marks_z"]

0    1.118723
1   -0.843949
2    0.569175
3   -0.843949
Name: Marks_z, dtype: float64

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

---

In [ ]:
# For descending rank
df["Rank"] = df["Marks"].rank(ascending=False)
df["Rank"]

0    1.0
1    3.5
2    2.0
3    3.5
Name: Rank, dtype: float64

In [ ]:
# Dense Ranking:- 

df["Rank"] = df["Marks"].rank(ascending=False,
    method="dense")

df["Rank"]

0    1.0
1    3.0
2    2.0
3    3.0
Name: Rank, dtype: float64

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

---

In [ ]:
# Equal width Bins:-
# cut() -> equal width

pd.cut(df["Marks"], bins=4)

0      (88.75, 95.0]
1    (69.975, 76.25]
2      (82.5, 88.75]
3    (69.975, 76.25]
Name: Marks, dtype: category
Categories (4, interval[float64, right]): [(69.975, 76.25] < (76.25, 82.5] < (82.5, 88.75] < (88.75, 95.0]]

In [ ]:
# Custom Bins:- 
pd.cut(df["Marks"], bins=[0,50,75,100],
    labels=["Low","Medium","High"])

0      High
1    Medium
2      High
3    Medium
Name: Marks, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

---

In [ ]:
# For equal-frequency (quantile-based) bins.
# cut() -> for equal width
# qcut() -> for equal frequency

pd.qcut(
    df["Marks"],
    q=4,
    duplicates="drop"  
)

0     (89.75, 95.0]
1    (69.999, 79.0]
2     (79.0, 89.75]
3    (69.999, 79.0]
Name: Marks, dtype: category
Categories (3, interval[float64, right]): [(69.999, 79.0] < (79.0, 89.75] < (89.75, 95.0]]

In [ ]:
# With label
df["Quartile"] = pd.qcut(
    df["Marks"],
    q=4,
    duplicates="drop",
    labels=["Low", "Medium", "High"]
)

df

     Name  Marks    City  Rank  Flag  Marks_norm   Marks_z Quartile
0   Rahul     95    Pune   1.0     1        1.00  1.118723     High
1  Ganraj     70  Mumbai   3.0     0        0.00 -0.843949      Low
2    Neha     88   Delhi   2.0     1        0.72  0.569175   Medium
3   Priya     70  Nashik   3.0     0        0.00 -0.843949      Low

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

---

In [ ]:
# For counting unique values
df["City"].nunique()

4

In [ ]:
# For frequency per unique value
df["City"].value_counts()

City
Pune      1
Mumbai    1
Delhi     1
Nashik    1
Name: count, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

---

In [ ]:
# replace() -> value mapping
# str.replace() -> text pattern replacement

df.replace({
    "City": {
        "Pune": "PUNE",
        "Mumbai": "MUMBAI"
    }
})

     Name  Marks    City  Rank
0   Rahul     95    PUNE   1.0
1  Ganraj     70  MUMBAI   3.0
2    Neha     88   Delhi   2.0
3   Priya     70  Nashik   3.0

In [ ]:
# By using list
df.replace(
    ["Pune", "Mumbai"],
    "INDIA"
)

     Name  Marks    City  Rank
0   Rahul     95   INDIA   1.0
1  Ganraj     70   INDIA   3.0
2    Neha     88   Delhi   2.0
3   Priya     70  Nashik   3.0

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

---

In [ ]:
# Boolean -> Integer
df["Flag"] = ( df["Marks"] > 80 ).astype(int)
df["Flag"]

0    1
1    0
2    1
3    0
Name: Flag, dtype: int64

In [ ]:
# By using np.where() condition

import numpy as np

df["Flag"] = np.where(df["Marks"] > 80,1,0)
df["Flag"]

0    1
1    0
2    1
3    0
Name: Flag, dtype: int64

## Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

---

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

---

In [ ]:
# how to access rows when vectorization is not possible:-
# iterrows() -> convert each row to a Series

for idx, row in df.iterrows():
    print(idx, row["Name"], row["Marks"])

0 Rahul 95
1 Ganraj 70
2 Neha 88
3 Priya 70

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

---

In [ ]:
# iterrows() -> slow
# itertuples() -> fast

# If iteration is not possible:
# itertuples() > iterrows()

for row in df.itertuples():
    print(row.Name, row.Marks)

Rahul 95
Ganraj 70
Neha 88
Priya 70

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

---

In [ ]:
# For accessing df[col]
for col in df.columns:
    print(col)

Name
Marks
City
Rank
Flag
Marks_norm
Marks_z
Quartile

In [ ]:
# By using df.items():- 
for col_name, series in df.items():
    print(col_name)

Name
Marks
City
Rank
Flag
Marks_norm
Marks_z
Quartile

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

---

In [ ]:
df["Bonus"] = df["Marks"] * 10
df["Bonus"]

0    950
1    700
2    880
3    700
Name: Bonus, dtype: int64

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

---

In [ ]:
df.groupby("City")["Marks"].mean()

City
Delhi     88.0
Mumbai    70.0
Nashik    70.0
Pune      95.0
Name: Marks, dtype: float64

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

---

In [ ]:
df.groupby("City")["Marks"].sum()

City
Delhi     88
Mumbai    70
Nashik    70
Pune      95
Name: Marks, dtype: int64

In [ ]:
df.groupby("City")["Marks"].mean()

City
Delhi     88.0
Mumbai    70.0
Nashik    70.0
Pune      95.0
Name: Marks, dtype: float64

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

---

In [ ]:
df.groupby("City").agg({
    "Marks": ["mean", "max", "min"]
})

       Marks
        mean max min
City
Delhi   88.0  88  88
Mumbai  70.0  70  70
Nashik  70.0  70  70
Pune    95.0  95  95

In [ ]:
# Named Aggregation -> creates cleaner output.
df.groupby("City").agg(
    Avg_Marks=("Marks", "mean"),
    Max_Marks=("Marks", "max")
)

        Avg_Marks  Max_Marks
City
Delhi        88.0         88
Mumbai       70.0         70
Nashik       70.0         70
Pune         95.0         95

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

---

In [ ]:
df.groupby(
    ["Name", "City"]
)["Marks"].mean()

Name    City
Ganraj  Mumbai    70.0
Neha    Delhi     88.0
Priya   Nashik    70.0
Rahul   Pune      95.0
Name: Marks, dtype: float64

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

---

In [ ]:
df.groupby("City").filter(
    lambda g: g["Marks"].mean() > 80
)

    Name  Marks   City  Rank  Flag  Marks_norm   Marks_z Quartile  Bonus
0  Rahul     95   Pune   1.0     1        1.00  1.118723     High    950
2   Neha     88  Delhi   2.0     1        0.72  0.569175   Medium    880

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

---

In [ ]:
# agg() -> output size reduced
# transform() -> same output size

df["City_Avg"] = (
    df.groupby("City")["Marks"]
      .transform("mean")
)

df["City_Avg"]

0    95.0
1    70.0
2    88.0
3    70.0
Name: City_Avg, dtype: float64

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

---

In [ ]:
df.groupby("City")["Marks"].agg(
    lambda s: s.max() - s.min()
)

City
Delhi     0
Mumbai    0
Nashik    0
Pune      0
Name: Marks, dtype: int64

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

---

In [ ]:
pd.pivot_table(
    df,
    values="Marks",
    index="City",
    aggfunc="mean"
)

        Marks
City
Delhi    88.0
Mumbai   70.0
Nashik   70.0
Pune     95.0

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

---

In [ ]:
pd.pivot_table(
    df,
    values="Marks",
    index="City",
    aggfunc=["mean", "max"]
)

        mean   max
       Marks Marks
City
Delhi   88.0    88
Mumbai  70.0    70
Nashik  70.0    70
Pune    95.0    95

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

---

In [ ]:
pd.pivot_table(
    df,
    values="Marks",
    index="City",
    fill_value=0
)

        Marks
City
Delhi    88.0
Mumbai   70.0
Nashik   70.0
Pune     95.0

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

---

In [ ]:
pd.pivot_table(
    df,
    values="Marks",
    index="City",
    margins=True,
    margins_name="TOTAL"
)

        Marks
City
Delhi   88.00
Mumbai  70.00
Nashik  70.00
Pune    95.00
TOTAL   80.75

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

---

In [ ]:
pd.pivot_table(
    df,
    values="Marks",
    index=["Name", "City"],
    aggfunc="mean"
)

               Marks
Name   City
Ganraj Mumbai   70.0
Neha   Delhi    88.0
Priya  Nashik   70.0
Rahul  Pune     95.0

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

---

In [ ]:
df.pivot(
    index="Name",
    columns="City",
    values="Marks"
)

City    Delhi  Mumbai  Nashik  Pune
Name
Ganraj    NaN    70.0     NaN   NaN
Neha     88.0     NaN     NaN   NaN
Priya     NaN     NaN    70.0   NaN
Rahul     NaN     NaN     NaN  95.0

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

---

#### Pivot vs GroupBy
- Analysis -> groupby()
- reporting -> pivot_table()

| Feature | groupby() | pivot_table() |
| ------------------ | --------- | ------------- |
| Flexible | More Flexible | Moderate |
| 2D Report | No | Yes |
| Aggregation | Possible | Possible |
| Handles Duplicates | Yes | Yes |
| Spreadsheet Style  | No | Yes |

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

---

In [ ]:
# For Summary report
report = (
    pd.pivot_table(
        df,
        values="Marks",
        index="City",
        aggfunc="mean",
        fill_value=0,
        margins=True
    )
    .round(2)
)

report

        Marks
City
Delhi   88.00
Mumbai  70.00
Nashik  70.00
Pune    95.00
All     80.75

In [ ]:
# Export a file
report.to_csv("report.csv")

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

---

In [ ]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,0
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,0,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# Production Pipeline:- 
# 1. Load
df = pd.read_csv("employees.csv")

# 2. Inspect
df.info()
df.describe()

# 3. Clean
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

# 4. Feature Engineering
df["Bonus"] = df["Salary"] * 0.1

# 5. Analysis
summary = (
    df.groupby("First Name")["Salary"]
      .mean()
)

# 6. Rank
summary = summary.sort_values(
    ascending=False
)

# 7. Export
summary.to_csv("output.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB